/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-03-03 10:18:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.members.mypage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class check_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jspf", Long.valueOf(1772500512000L));
    _jspx_dependants.put("/WEB-INF/views/common/findPasswordModal.jspf", Long.valueOf(1772500512000L));
    _jspx_dependants.put("/WEB-INF/views/common/loginRequiredModal.jspf", Long.valueOf(1772500512000L));
    _jspx_dependants.put("/WEB-INF/views/common/signupModal.jspf", Long.valueOf(1772526452000L));
    _jspx_dependants.put("file:/C:/Users/ddd04/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1767668479510L));
    _jspx_dependants.put("/WEB-INF/views/common/theme.jspf", Long.valueOf(1772500512000L));
    _jspx_dependants.put("jar:file:/C:/Users/ddd04/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/views/common/authModal.jspf", Long.valueOf(1772500512000L));
    _jspx_dependants.put("/WEB-INF/views/common/loginModal.jspf", Long.valueOf(1772526424000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/theme-init.js\"></script>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>비밀번호 확인</title>\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/redesign.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/ui-toast.css\" />\r\n");
      out.write("\r\n");
      out.write("  <script defer src=\"/js/ui-toast.js\"></script>\r\n");
      out.write("  <script defer src=\"/js/theme.js\"></script>\r\n");
      out.write("  <script defer src=\"/js/nav-wave.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"page-solid\">\r\n");
      out.write("	\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mp-shell\">\r\n");
      out.write("  <aside class=\"mp-side\">\r\n");
      out.write("    <nav class=\"mp-nav\">\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage\">\r\n");
      out.write("        <span class=\"mp-ico\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M4 13h7V4H4v9Zm9 7h7V11h-7v9ZM4 20h7v-5H4v5Zm9-16v5h7V4h-7Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg></span>대시보드\r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/check\">\r\n");
      out.write("        <span class=\"mp-ico\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M12 20h9\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4 11.5-11.5Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg></span>회원정보 수정\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/plans\">\r\n");
      out.write("        <span class=\"mp-ico\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M7 3v3M17 3v3\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M4 8h16\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M5 6h14a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg></span>내 여행 계획\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/reviews\">\r\n");
      out.write("        <span class=\"mp-ico\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M7 3h8l4 4v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/><path d=\"M15 3v5h5\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/><path d=\"M8 13h8M8 17h8\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/></svg></span>내 여행 후기\r\n");
      out.write("      </a>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/wishlist\">\r\n");
      out.write("        <span class=\"mp-ico\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/></svg></span>내 찜 목록\r\n");
      out.write("      </a>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"mp-main\">\r\n");
      out.write("    <section class=\"mp-card mp-grow\" style=\"width: 100%;\">\r\n");
      out.write("      <div class=\"mp-card-head\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <div class=\"mp-card-title\">비밀번호 확인</div>\r\n");
      out.write("          <div class=\"mp-card-sub\">회원정보 수정을 위해 비밀번호를 입력해 주세요</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mp-card-body\" style=\"width: 100%; text-align: center; padding: 60px 20px;\">\r\n");
      out.write("        <form class=\"mp-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/check\" method=\"post\">\r\n");
      out.write("          <div class=\"mp-field\">\r\n");
      out.write("            <label>비밀번호</label>\r\n");
      out.write("            <input type=\"password\" name=\"password\" placeholder=\"현재 비밀번호를 입력하세요\" required />\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"mp-actions\">\r\n");
      out.write("            <button class=\"mp-btn\" type=\"submit\">확인</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("  .ptf-footer{\n");
      out.write("    margin-top:auto; /* ✅ 짧은 페이지에서 하단 고정 */\n");
      out.write("    padding-bottom: 24px;\n");
      out.write("    background:#fff;\n");
      out.write("    color:#111827;\n");
      out.write("    position:relative;\n");
      out.write("    z-index:10;\n");
      out.write("    margin-top:0;\n");
      out.write("    /* ✅ 전체 페이지 공통 footer: 가로 스크롤(100vw) 방지 */\n");
      out.write("    width:100%;\n");
      out.write("    margin-left:0;\n");
      out.write("    box-sizing:border-box;\n");
      out.write("    overflow-x:hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("  /* 상단 파란 포인트 라인(그대로 유지) */\n");
      out.write("  .ptf-footer__topbar{\n");
      out.write("    height:3px;\n");
      out.write("    background: linear-gradient(90deg,#2f6fed 0%, #5b8cff 50%, #2f6fed 100%);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* 링크 메뉴 영역(그대로 유지) */\n");
      out.write("  .ptf-footer__nav{\n");
      out.write("    border-bottom:1px solid #e5e7eb;\n");
      out.write("    padding:14px 0;\n");
      out.write("    background:#fff;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px;\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:space-between;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("    gap:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links a{\n");
      out.write("    font-size:13px;\n");
      out.write("    font-weight:600;\n");
      out.write("    color:#374151;\n");
      out.write("    text-decoration:none;\n");
      out.write("    padding:4px 14px;\n");
      out.write("    border-right:1px solid #d1d5db;\n");
      out.write("    transition:color .15s;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links a:first-child{ padding-left:0; }\n");
      out.write("  .ptf-footer__nav-links a:last-child{ border-right:none; }\n");
      out.write("  .ptf-footer__nav-links a:hover{ color:#2f6fed; }\n");
      out.write("  .ptf-footer__nav-links a.pt-highlight{\n");
      out.write("    color:#2f6fed;\n");
      out.write("    font-weight:800;\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" /* ========== 메인 정보 영역 (로고 + 프로젝트 정보) ========== */\n");
      out.write("  /* 메인 정보 영역(큰 박스) */\n");
      out.write("  .ptf-footer__body{\n");
      out.write("    padding:32px 0 0;              /* ✅ 아래는 bottombar가 따로 있으니 0 */\n");
      out.write("    border-bottom:1px solid #e5e7eb;\n");
      out.write("    background:#fff;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__body-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px 22px;           /* ✅ 박스 안 내용 아래 여백 */\n");
      out.write("    display:grid;\n");
      out.write("    grid-template-columns:220px 1fr;\n");
      out.write("    gap:48px;\n");
      out.write("    align-items:start;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .ptf-footer__brand-logo{\n");
      out.write("    font-size:24px;\n");
      out.write("    font-weight:900;\n");
      out.write("    color:#111827;\n");
      out.write("    letter-spacing:-.3px;\n");
      out.write("    margin-bottom:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__brand-logo span{ color:#2f6fed; }\n");
      out.write("\n");
      out.write("/* ---- 왼쪽: 브랜드 설명 텍스트 ---- */\n");
      out.write("  .ptf-footer__brand-desc{\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#6b7280;\n");
      out.write("    line-height:1.6;\n");
      out.write("    margin:0;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("/* ---- 오른쪽: 프로젝트 정보 영역 ---- */\n");
      out.write("  .ptf-footer__info{\n");
      out.write("    display:flex;\n");
      out.write("    flex-direction:column;\n");
      out.write("    gap:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__info-row{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("    gap:6px 20px;\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#374151;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__info-row .pt-sep{ color:#d1d5db; }\n");
      out.write("  .ptf-footer__info-row strong{ font-weight:700; color:#111827; }\n");
      out.write("\n");
      out.write("  .ptf-footer__contact-item{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    gap:6px;\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#374151;\n");
      out.write("    margin-top:4px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__contact-item a{\n");
      out.write("    color:#374151;\n");
      out.write("    text-decoration:underline;\n");
      out.write("    text-underline-offset:3px;\n");
      out.write("    transition:color .15s;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__contact-item a:hover{ color:#2f6fed; }\n");
      out.write("  .ptf-footer__contact-item .pt-icon{\n");
      out.write("    width:18px;\n");
      out.write("    height:18px;\n");
      out.write("    background:#f3f4f6;\n");
      out.write("    border-radius:50%;\n");
      out.write("    display:inline-flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:center;\n");
      out.write("    font-size:10px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ✅ 동그라미 문구를 \"화살표 박스 안\"에 붙이는 하단 바 */\n");
      out.write("  .ptf-footer__bottombar{\n");
      out.write("    background:#f3f4f6;                 /* ✅ 회색(연한) 배경으로 '붙어' 보이게 */\n");
      out.write("    border-top:1px solid #e5e7eb;       /* ✅ 박스 안에서 딱 붙는 구분선 */\n");
      out.write("    padding:12px 0;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__bottombar-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px;\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:space-between;      /* ✅ 좌/우 */\n");
      out.write("    gap:16px;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__copy,\n");
      out.write("  .ptf-footer__note{\n");
      out.write("    margin:0;\n");
      out.write("    font-size:13px;\n");
      out.write("    line-height:1.5;\n");
      out.write("    color:rgba(17,24,39,.70);\n");
      out.write("  }\n");
      out.write("  .ptf-footer__note{ text-align:right; }\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("  @media (max-width:860px){\n");
      out.write("    .ptf-footer__body-inner{ grid-template-columns:1fr; gap:24px; }\n");
      out.write("    .ptf-footer__nav-links a{ font-size:12px; padding:4px 10px; }\n");
      out.write("  }\n");
      out.write("  @media (max-width:768px){\n");
      out.write("    .ptf-footer__bottombar-inner{\n");
      out.write("      flex-direction:column;\n");
      out.write("      align-items:flex-start;\n");
      out.write("    }\n");
      out.write("    .ptf-footer__note{ text-align:left; }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ===== Floating 고객센터 (기존 UI 그대로) ===== */\n");
      out.write("  .cs-fab{\n");
      out.write("    position:fixed;\n");
      out.write("    right:26px;\n");
      out.write("    bottom:26px;\n");
      out.write("    z-index:9999;\n");
      out.write("    height:56px;\n");
      out.write("    min-width:78px;\n");
      out.write("    padding:10px 14px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    background:rgba(47,111,237,.92);\n");
      out.write("    backdrop-filter:blur(6px);\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.18);\n");
      out.write("    display:inline-flex;\n");
      out.write("    align-items:center;\n");
      out.write("    gap:10px;\n");
      out.write("    border:1px solid rgba(255,255,255,.18);\n");
      out.write("    user-select:none;\n");
      out.write("    -webkit-tap-highlight-color:transparent;\n");
      out.write("    text-decoration:none;\n");
      out.write("  }\n");
      out.write("  .cs-fab__icon{\n");
      out.write("    width:38px;\n");
      out.write("    height:38px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    background:#fff;\n");
      out.write("    color:#2f6fed;\n");
      out.write("    display:grid;\n");
      out.write("    place-items:center;\n");
      out.write("    font-weight:900;\n");
      out.write("    font-size:18px;\n");
      out.write("    flex:0 0 auto;\n");
      out.write("  }\n");
      out.write("  .cs-fab__label{\n");
      out.write("    color:#fff;\n");
      out.write("    font-weight:900;\n");
      out.write("    font-size:14px;\n");
      out.write("    letter-spacing:-.2px;\n");
      out.write("    max-width:0;\n");
      out.write("    opacity:0;\n");
      out.write("    transform:translateX(6px);\n");
      out.write("    overflow:hidden;\n");
      out.write("    white-space:nowrap;\n");
      out.write("    transition:max-width .22s ease, opacity .18s ease, transform .22s ease;\n");
      out.write("  }\n");
      out.write("  .cs-fab:hover{\n");
      out.write("    background:rgba(47,111,237,1);\n");
      out.write("    transform:translateY(-2px);\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.22);\n");
      out.write("  }\n");
      out.write("  .cs-fab:hover .cs-fab__label{\n");
      out.write("    max-width:140px;\n");
      out.write("    opacity:1;\n");
      out.write("    transform:translateX(0);\n");
      out.write("  }\n");
      out.write("  .cs-fab:focus-visible{\n");
      out.write("    outline:none;\n");
      out.write("    box-shadow:0 0 0 4px rgba(47,111,237,.25), 0 22px 50px rgba(0,0,0,.22);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ===== 맨 위로 버튼 (고객센터 위에) ===== */\n");
      out.write("  .top-fab{\n");
      out.write("    position:fixed;\n");
      out.write("    right:26px;\n");
      out.write("    bottom:92px; /* 고객센터 위 */\n");
      out.write("    z-index:9999;\n");
      out.write("    width:56px;\n");
      out.write("    height:56px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    border:1px solid rgba(17,24,39,.10);\n");
      out.write("    background:#fff;\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.14);\n");
      out.write("    display:none; /* 스크롤 시 JS로 표시 */\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:center;\n");
      out.write("    cursor:pointer;\n");
      out.write("    -webkit-tap-highlight-color:transparent;\n");
      out.write("  }\n");
      out.write("  .top-fab:hover{\n");
      out.write("    transform:translateY(-2px);\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.18);\n");
      out.write("  }\n");
      out.write("  .top-fab svg{\n");
      out.write("    width:22px;\n");
      out.write("    height:22px;\n");
      out.write("    stroke:#2f6fed;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<footer class=\"ptf-footer\" role=\"contentinfo\">\n");
      out.write("\n");
      out.write("  <!-- 상단 포인트 라인 -->\n");
      out.write("  <div class=\"ptf-footer__topbar\"></div>\n");
      out.write("\n");
      out.write("  <!-- 링크 메뉴 -->\n");
      out.write("  <nav class=\"ptf-footer__nav\">\n");
      out.write("    <div class=\"ptf-footer__nav-inner\">\n");
      out.write("      <div class=\"ptf-footer__nav-links\">\n");
      out.write("        <a href=\"#\" class=\"pt-highlight\">개인정보 취급방침</a>\n");
      out.write("        <a href=\"#\">이용약관</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <!-- 메인 정보(화살표 친 큰 박스) -->\n");
      out.write("  <div class=\"ptf-footer__body\">\n");
      out.write("    <div class=\"ptf-footer__body-inner\">\n");
      out.write("\n");
      out.write("      <div class=\"ptf-footer__brand\">\n");
      out.write("        <div class=\"ptf-footer__brand-logo\">Plan<span>Trip</span></div>\n");
      out.write("        <p class=\"ptf-footer__brand-desc\">\n");
      out.write("          나만의 여행을 더 쉽게,<br>더 똑똑하게.\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"ptf-footer__info\">\n");
      out.write("        <div class=\"ptf-footer__info-row\">\n");
      out.write("          <span>프로젝트 : <strong>PlanTrip (교육용 팀 프로젝트)</strong></span>\n");
      out.write("          <span class=\"pt-sep\">|</span>\n");
      out.write("          <span>소속 : <strong>백석대학교</strong></span>\n");
      out.write("          <span class=\"pt-sep\">|</span>\n");
      out.write("          <span>강의실 : <strong>214호</strong></span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"ptf-footer__info-row\">\n");
      out.write("          <span>충청남도 천안시 동남구 백석대학로 1 &nbsp;백석대학교 (214호 강의실)</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"ptf-footer__contact-item\">\n");
      out.write("          <span class=\"pt-icon\">✉</span>\n");
      out.write("          <a href=\"mailto:plantrip.team@baekseok.ac.kr\">plantrip.team@baekseok.ac.kr</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- ✅ 동그라미 문구를 \"화살표 박스 안\" 맨 아래에 붙임 -->\n");
      out.write("    <div class=\"ptf-footer__bottombar\">\n");
      out.write("      <div class=\"ptf-footer__bottombar-inner\">\n");
      out.write("        <p class=\"ptf-footer__copy\">© <span id=\"ptFooterYear\"></span> PlanTrip. All Rights Reserved.</p>\n");
      out.write("        <p class=\"ptf-footer__note\">본 사이트는 교육용 프로젝트이며 실제 예약/결제 기능을 제공하지 않습니다.</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Floating: 맨 위로 / 고객센터 -->\n");
      out.write("<button class=\"top-fab\" type=\"button\" aria-label=\"맨 위로\">\n");
      out.write("  <svg viewBox=\"0 0 24 24\" fill=\"none\" aria-hidden=\"true\">\n");
      out.write("    <path d=\"M12 5l-7 7m7-7l7 7M12 5v14\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\n");
      out.write("  </svg>\n");
      out.write("</button>\n");
      out.write("\n");
      out.write("<a class=\"cs-fab\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/support\" aria-label=\"고객센터\">\n");
      out.write("  <span class=\"cs-fab__icon\" aria-hidden=\"true\">?</span>\n");
      out.write("  <span class=\"cs-fab__label\">고객센터</span>\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  document.body.setAttribute('data-ctx', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/fabs.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  (function(){\n");
      out.write("    var el = document.getElementById('ptFooterYear');\n");
      out.write("    if(el) el.textContent = new Date().getFullYear();\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- ✅ Toast UI : 전 페이지 공통 (로그인/저장/안내 메시지) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/ui-toast.css\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/ui-toast.js\"></script>\n");
      out.write("\n");
      out.write("<!-- ✅ Auth Modal (Login/Signup) : 전 페이지 공통 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/auth-modal.css\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-modal.js\"></script>\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-guard.js\"></script>\n");
      out.write("<!-- auth-modal ê³µíµ include -->\n");
      out.write("\n");
      out.write("<!-- 로그인 모달 -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-login\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authLoginTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\n");
      out.write("\n");
      out.write("    <!-- ✅ dialog 전체에 깔리는 물결 배경 -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-wrap auth-wrap--split\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authLoginTitle\">로그인</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/login\" method=\"post\">\n");
      out.write("          <div class=\"label\">아이디</div>\n");
      out.write("          <input class=\"input\" name=\"id\" type=\"text\" placeholder=\"아이디\" required />\n");
      out.write("          <!-- ✅ 필드 옆 에러(레이아웃 고정용) -->\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"id\"></div>\n");
      out.write("\n");
      out.write("          <div class=\"label\">비밀번호</div>\n");
      out.write("          <div class=\"input-row\">\n");
      out.write("            <input class=\"input\" name=\"password\" type=\"password\" placeholder=\"비밀번호\" required />\n");
      out.write("            <button class=\"eye\" type=\"button\" aria-label=\"비밀번호 보기\" aria-pressed=\"false\">\n");
      out.write("  <!-- eye-open -->\n");
      out.write("  <svg class=\"eye-ic eye-ic--open\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\n");
      out.write("    <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8s8.2 3.4 9.8 8c-1.6 4.6-5.8 8-9.8 8s-8.2-3.4-9.8-8Z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\n");
      out.write("    <circle cx=\"12\" cy=\"12\" r=\"3.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>\n");
      out.write("  </svg>\n");
      out.write("\n");
      out.write("  <!-- eye-off -->\n");
      out.write("  <svg class=\"eye-ic eye-ic--off\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\n");
      out.write("    <path d=\"M3 3l18 18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\n");
      out.write("    <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8 2.2 0 4.4.9 6.2 2.3M21.8 12c-1.6 4.6-5.8 8-9.8 8-2.2 0-4.4-.9-6.2-2.3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\n");
      out.write("    <path d=\"M10.2 10.2A3.2 3.2 0 0 0 12 15.2c.5 0 1-.1 1.4-.3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\n");
      out.write("  </svg>\n");
      out.write("</button>\n");
      out.write("          </div>\n");
      out.write("          <!-- ✅ 필드 옆 에러(레이아웃 고정용) -->\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"password\"></div>\n");
      out.write("\n");
      out.write("          <div style=\"text-align:right; margin-top:-6px;\">\n");
      out.write("            <a class=\"underline small\" href=\"/members/find-password\" data-auth-switch=\"find\">비밀번호를 잊으셨나요?</a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <!-- (예외 상황용) 공통 에러: 박스 없이 텍스트만 출력 -->\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">로그인</button>\n");
      out.write("\n");
      out.write("          <div class=\"social-row\">\n");
      out.write("  			<a class=\"social-btn\"\n");
      out.write("     			href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/oauth2/authorization/google\">\n");
      out.write("    		<span class=\"social-icon\" aria-hidden=\"true\">\n");
      out.write("      			<span class=\"social-dot\"></span>\n");
      out.write("    </span>\n");
      out.write("    		<span class=\"social-text\">구글</span>\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <button class=\"social-btn\" type=\"button\">\n");
      out.write("    <span class=\"social-icon\" aria-hidden=\"true\">\n");
      out.write("      <span class=\"social-dot\"></span>\n");
      out.write("    </span>\n");
      out.write("    <span class=\"social-text\">페이스북</span>\n");
      out.write("  </button>\n");
      out.write("</div>\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            계정이 없으신가요?\n");
      out.write("            <a class=\"underline\" href=\"/members/register\" data-auth-switch=\"signup\"><b>회원가입</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("\n");
      out.write("<!-- 회원가입 모달 -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-signup\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authSignupTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\n");
      out.write("\n");
      out.write("    <!-- dialog 전체에 깔리는 물결/물방울 배경 (회원가입은 CSS에서 “왼쪽” 앵커 처리됨) -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <!-- [수정] 회원가입은 폼이 오른쪽으로 가야 하므로 auth-wrap--swap 사용 -->\n");
      out.write("    <div class=\"auth-wrap auth-wrap--swap\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authSignupTitle\">회원가입</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/register\" method=\"post\">\n");
      out.write("          <!-- (예외 상황용) 공통 에러: 박스 없이 텍스트만 출력 -->\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <div class=\"label\">이름</div>\n");
      out.write("          <input class=\"input\" name=\"mName\" type=\"text\" placeholder=\"이름\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">아이디</div>\n");
      out.write("          <input class=\"input\" name=\"mId\" type=\"text\" placeholder=\"아이디\" required />\n");
      out.write("          <!-- ✅ 중복 아이디/형식 에러 -->\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"mId\"></div>\n");
      out.write("\n");
      out.write("          <div class=\"label\">이메일</div>\n");
      out.write("          <input class=\"input\" name=\"mEmail\" type=\"email\" placeholder=\"이메일\" required />\n");
      out.write("          <!-- ✅ 중복 이메일/형식 에러 -->\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"mEmail\"></div>\n");
      out.write("\n");
      out.write("         <div class=\"label\">비밀번호</div>\n");
      out.write("<div class=\"input-row\">\n");
      out.write("  <input class=\"input\" name=\"mPw\" type=\"password\" placeholder=\"비밀번호\" required />\n");
      out.write("\n");
      out.write("  <button class=\"eye\" type=\"button\" aria-label=\"비밀번호 보기\" aria-pressed=\"false\">\n");
      out.write("    <!-- eye-open -->\n");
      out.write("    <svg class=\"eye-ic eye-ic--open\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\n");
      out.write("      <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8s8.2 3.4 9.8 8c-1.6 4.6-5.8 8-9.8 8s-8.2-3.4-9.8-8Z\"\n");
      out.write("            fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\n");
      out.write("      <circle cx=\"12\" cy=\"12\" r=\"3.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>\n");
      out.write("    </svg>\n");
      out.write("\n");
      out.write("    <!-- eye-off -->\n");
      out.write("    <svg class=\"eye-ic eye-ic--off\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\n");
      out.write("      <path d=\"M3 3l18 18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\n");
      out.write("      <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8 2.2 0 4.4.9 6.2 2.3M21.8 12c-1.6 4.6-5.8 8-9.8 8-2.2 0-4.4-.9-6.2-2.3\"\n");
      out.write("            fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\n");
      out.write("      <path d=\"M10.2 10.2A3.2 3.2 0 0 0 12 15.2c.5 0 1-.1 1.4-.3\"\n");
      out.write("            fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\n");
      out.write("    </svg>\n");
      out.write("  </button>\n");
      out.write("</div>\n");
      out.write("          <!-- ✅ 비밀번호 관련 에러(필요 시) -->\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"mPw\"></div>\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">회원가입</button>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            이미 회원이신가요?\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>로그인</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- [수정] 오른쪽(또는 왼쪽) 빈 자리용: 배경은 wave-bg가 담당 -->\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("<!-- 비밀번호 찾기(재설정 링크) 모달 -->\n");
      out.write("\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-find\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authFindTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\n");
      out.write("\n");
      out.write("    <!-- ✅ dialog 전체 물결 배경(센터 정렬 버전) -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-wrap auth-wrap--center\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authFindTitle\">비밀번호 찾기</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/find-password\" method=\"post\" data-find-form>\n");
      out.write("          <div class=\"label\">가입 이메일</div>\n");
      out.write("          <input class=\"input\" name=\"email\" type=\"email\" placeholder=\"example@email.com\" required />\n");
      out.write("\n");
      out.write("          <div class=\"helper\">\n");
      out.write("            입력하신 이메일로 <b>비밀번호 재설정 링크</b>를 보내드립니다.<br/>\n");
      out.write("            링크는 일정 시간 후 만료됩니다.\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">재설정 링크 받기</button>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>로그인으로</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("\n");
      out.write("<div class=\"lr-modal\" id=\"loginRequiredModal\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"lr-backdrop\" data-lr-close></div>\n");
      out.write("\n");
      out.write("  <div class=\"lr-dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"lrTitle\" tabindex=\"-1\">\n");
      out.write("    <div class=\"lr-icon\" aria-hidden=\"true\">🔒</div>\n");
      out.write("    <h2 class=\"lr-title\" id=\"lrTitle\">로그인이 필요한 작업입니다</h2>\n");
      out.write("    <p class=\"lr-desc\" id=\"lrDesc\">계속하려면 로그인해 주세요.</p>\n");
      out.write("\n");
      out.write("    <div class=\"lr-actions\">\n");
      out.write("      <button type=\"button\" class=\"lr-btn ghost\" data-lr-cancel>취소</button>\n");
      out.write("      <button type=\"button\" class=\"lr-btn solid\" data-lr-confirm>확인</button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/members/mypage/check.jsp(61,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"mp-error-text\" style=\"color: #ef4444; font-size: 14px; font-weight: 600; margin-bottom: 12px; display: block;\">");
        if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</div>\r\n");
        out.write("          ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/members/mypage/check.jsp(62,135) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
