/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-03-06 01:34:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.members.mypage;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class plans_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:length", org.apache.taglibs.standard.functions.Functions.class, "length", new Class[] {java.lang.Object.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/views/common/footer.jspf", Long.valueOf(1772759563973L));
    _jspx_dependants.put("/WEB-INF/views/common/findPasswordModal.jspf", Long.valueOf(1772759563971L));
    _jspx_dependants.put("/WEB-INF/views/common/loginRequiredModal.jspf", Long.valueOf(1772759563977L));
    _jspx_dependants.put("file:/C:/Users/knh66/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1767668468613L));
    _jspx_dependants.put("/WEB-INF/views/common/signupModal.jspf", Long.valueOf(1772759563979L));
    _jspx_dependants.put("/WEB-INF/views/common/theme.jspf", Long.valueOf(1772759563980L));
    _jspx_dependants.put("/WEB-INF/views/common/authModal.jspf", Long.valueOf(1772759563970L));
    _jspx_dependants.put("/WEB-INF/views/common/loginModal.jspf", Long.valueOf(1772759563976L));
    _jspx_dependants.put("jar:file:/C:/Users/knh66/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("jar:file:/C:/Users/knh66/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/theme-init.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("  <title>내 여행 계획</title>\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/mypage.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/redesign.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/ui-toast.css\" />\r\n");
      out.write("\r\n");
      out.write("  <script defer src=\"/js/ui-toast.js\"></script>\r\n");
      out.write("  <script defer src=\"/js/theme.js\"></script>\r\n");
      out.write("  <script defer src=\"/js/nav-wave.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"page-solid\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mp-shell\">\r\n");
      out.write("  <aside class=\"mp-side\">\r\n");
      out.write("    <div class=\"sec\" style=\"padding-top: 20px;\">\r\n");
      out.write("      <nav class=\"mp-nav\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage\">\r\n");
      out.write("          <span class=\"mp-ico\" aria-hidden=\"true\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M4 13h7V4H4v9Zm9 7h7V11h-7v9ZM4 20h7v-5H4v5Zm9-16v5h7V4h-7Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg>\r\n");
      out.write("          </span>대시보드\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/check\">\r\n");
      out.write("          <span class=\"mp-ico\" aria-hidden=\"true\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M12 20h9\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4 11.5-11.5Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg>\r\n");
      out.write("          </span>회원정보 수정\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/plans\">\r\n");
      out.write("          <span class=\"mp-ico\" aria-hidden=\"true\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M7 3v3M17 3v3\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M4 8h16\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M5 6h14a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg>\r\n");
      out.write("          </span>내 여행 계획\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/reviews\">\r\n");
      out.write("          <span class=\"mp-ico\" aria-hidden=\"true\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M7 3h8l4 4v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/><path d=\"M15 3v5h5\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/><path d=\"M8 13h8M8 17h8\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/></svg>\r\n");
      out.write("          </span>내 여행 후기\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/members/mypage/wishlist\">\r\n");
      out.write("          <span class=\"mp-ico\" aria-hidden=\"true\">\r\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\"><path d=\"M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/></svg>\r\n");
      out.write("          </span>내 찜 목록\r\n");
      out.write("        </a>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("  </aside>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"mp-main\">\r\n");
      out.write("    <section class=\"mp-card mp-grow\" style=\"width: 100%;\">\r\n");
      out.write("      <div class=\"mp-card-head\" style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <div class=\"mp-card-title\">내 여행 계획</div>\r\n");
      out.write("          <div class=\"mp-card-sub\">작성한 계획 목록입니다.</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"font-size: 14px; color: #555;\">\r\n");
      out.write("          총 <b style=\"color: #3264ff;\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</b>건\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"mp-card-body\" style=\"width: 100%;\">\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </main>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  .ptf-footer{\r\n");
      out.write("    margin-top:auto; /* ✅ 짧은 페이지에서 하단 고정 */\r\n");
      out.write("    padding-bottom: 24px;\r\n");
      out.write("    background:#fff;\r\n");
      out.write("    color:#111827;\r\n");
      out.write("    position:relative;\r\n");
      out.write("    z-index:10;\r\n");
      out.write("    margin-top:0;\r\n");
      out.write("    /* ✅ 전체 페이지 공통 footer: 가로 스크롤(100vw) 방지 */\r\n");
      out.write("    width:100%;\r\n");
      out.write("    margin-left:0;\r\n");
      out.write("    box-sizing:border-box;\r\n");
      out.write("    overflow-x:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("  /* 상단 파란 포인트 라인(그대로 유지) */\r\n");
      out.write("  .ptf-footer__topbar{\r\n");
      out.write("    height:3px;\r\n");
      out.write("    background: linear-gradient(90deg,#2f6fed 0%, #5b8cff 50%, #2f6fed 100%);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* 링크 메뉴 영역(그대로 유지) */\r\n");
      out.write("  .ptf-footer__nav{\r\n");
      out.write("    border-bottom:1px solid #e5e7eb;\r\n");
      out.write("    padding:14px 0;\r\n");
      out.write("    background:#fff;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__nav-inner{\r\n");
      out.write("    max-width:1200px;\r\n");
      out.write("    margin:0 auto;\r\n");
      out.write("    padding:0 24px;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    justify-content:space-between;\r\n");
      out.write("    flex-wrap:wrap;\r\n");
      out.write("    gap:10px;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__nav-links{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    flex-wrap:wrap;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__nav-links a{\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("    font-weight:600;\r\n");
      out.write("    color:#374151;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    padding:4px 14px;\r\n");
      out.write("    border-right:1px solid #d1d5db;\r\n");
      out.write("    transition:color .15s;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__nav-links a:first-child{ padding-left:0; }\r\n");
      out.write("  .ptf-footer__nav-links a:last-child{ border-right:none; }\r\n");
      out.write("  .ptf-footer__nav-links a:hover{ color:#2f6fed; }\r\n");
      out.write("  .ptf-footer__nav-links a.pt-highlight{\r\n");
      out.write("    color:#2f6fed;\r\n");
      out.write("    font-weight:800;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" /* ========== 메인 정보 영역 (로고 + 프로젝트 정보) ========== */\r\n");
      out.write("  /* 메인 정보 영역(큰 박스) */\r\n");
      out.write("  .ptf-footer__body{\r\n");
      out.write("    padding:32px 0 0;              /* ✅ 아래는 bottombar가 따로 있으니 0 */\r\n");
      out.write("    border-bottom:1px solid #e5e7eb;\r\n");
      out.write("    background:#fff;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__body-inner{\r\n");
      out.write("    max-width:1200px;\r\n");
      out.write("    margin:0 auto;\r\n");
      out.write("    padding:0 24px 22px;           /* ✅ 박스 안 내용 아래 여백 */\r\n");
      out.write("    display:grid;\r\n");
      out.write("    grid-template-columns:220px 1fr;\r\n");
      out.write("    gap:48px;\r\n");
      out.write("    align-items:start;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .ptf-footer__brand-logo{\r\n");
      out.write("    font-size:24px;\r\n");
      out.write("    font-weight:900;\r\n");
      out.write("    color:#111827;\r\n");
      out.write("    letter-spacing:-.3px;\r\n");
      out.write("    margin-bottom:10px;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__brand-logo span{ color:#2f6fed; }\r\n");
      out.write("\r\n");
      out.write("/* ---- 왼쪽: 브랜드 설명 텍스트 ---- */\r\n");
      out.write("  .ptf-footer__brand-desc{\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("    color:#6b7280;\r\n");
      out.write("    line-height:1.6;\r\n");
      out.write("    margin:0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("/* ---- 오른쪽: 프로젝트 정보 영역 ---- */\r\n");
      out.write("  .ptf-footer__info{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    flex-direction:column;\r\n");
      out.write("    gap:10px;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__info-row{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    flex-wrap:wrap;\r\n");
      out.write("    gap:6px 20px;\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("    color:#374151;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__info-row .pt-sep{ color:#d1d5db; }\r\n");
      out.write("  .ptf-footer__info-row strong{ font-weight:700; color:#111827; }\r\n");
      out.write("\r\n");
      out.write("  .ptf-footer__contact-item{\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    gap:6px;\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("    color:#374151;\r\n");
      out.write("    margin-top:4px;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__contact-item a{\r\n");
      out.write("    color:#374151;\r\n");
      out.write("    text-decoration:underline;\r\n");
      out.write("    text-underline-offset:3px;\r\n");
      out.write("    transition:color .15s;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__contact-item a:hover{ color:#2f6fed; }\r\n");
      out.write("  .ptf-footer__contact-item .pt-icon{\r\n");
      out.write("    width:18px;\r\n");
      out.write("    height:18px;\r\n");
      out.write("    background:#f3f4f6;\r\n");
      out.write("    border-radius:50%;\r\n");
      out.write("    display:inline-flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    font-size:10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* ✅ 동그라미 문구를 \"화살표 박스 안\"에 붙이는 하단 바 */\r\n");
      out.write("  .ptf-footer__bottombar{\r\n");
      out.write("    background:#f3f4f6;                 /* ✅ 회색(연한) 배경으로 '붙어' 보이게 */\r\n");
      out.write("    border-top:1px solid #e5e7eb;       /* ✅ 박스 안에서 딱 붙는 구분선 */\r\n");
      out.write("    padding:12px 0;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__bottombar-inner{\r\n");
      out.write("    max-width:1200px;\r\n");
      out.write("    margin:0 auto;\r\n");
      out.write("    padding:0 24px;\r\n");
      out.write("    display:flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    justify-content:space-between;      /* ✅ 좌/우 */\r\n");
      out.write("    gap:16px;\r\n");
      out.write("    flex-wrap:wrap;\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__copy,\r\n");
      out.write("  .ptf-footer__note{\r\n");
      out.write("    margin:0;\r\n");
      out.write("    font-size:13px;\r\n");
      out.write("    line-height:1.5;\r\n");
      out.write("    color:rgba(17,24,39,.70);\r\n");
      out.write("  }\r\n");
      out.write("  .ptf-footer__note{ text-align:right; }\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  @media (max-width:860px){\r\n");
      out.write("    .ptf-footer__body-inner{ grid-template-columns:1fr; gap:24px; }\r\n");
      out.write("    .ptf-footer__nav-links a{ font-size:12px; padding:4px 10px; }\r\n");
      out.write("  }\r\n");
      out.write("  @media (max-width:768px){\r\n");
      out.write("    .ptf-footer__bottombar-inner{\r\n");
      out.write("      flex-direction:column;\r\n");
      out.write("      align-items:flex-start;\r\n");
      out.write("    }\r\n");
      out.write("    .ptf-footer__note{ text-align:left; }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* ===== Floating 고객센터 (기존 UI 그대로) ===== */\r\n");
      out.write("  .cs-fab{\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    right:26px;\r\n");
      out.write("    bottom:26px;\r\n");
      out.write("    z-index:9999;\r\n");
      out.write("    height:56px;\r\n");
      out.write("    min-width:78px;\r\n");
      out.write("    padding:10px 14px;\r\n");
      out.write("    border-radius:999px;\r\n");
      out.write("    background:rgba(47,111,237,.92);\r\n");
      out.write("    backdrop-filter:blur(6px);\r\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.18);\r\n");
      out.write("    display:inline-flex;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    gap:10px;\r\n");
      out.write("    border:1px solid rgba(255,255,255,.18);\r\n");
      out.write("    user-select:none;\r\n");
      out.write("    -webkit-tap-highlight-color:transparent;\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("  }\r\n");
      out.write("  .cs-fab__icon{\r\n");
      out.write("    width:38px;\r\n");
      out.write("    height:38px;\r\n");
      out.write("    border-radius:999px;\r\n");
      out.write("    background:#fff;\r\n");
      out.write("    color:#2f6fed;\r\n");
      out.write("    display:grid;\r\n");
      out.write("    place-items:center;\r\n");
      out.write("    font-weight:900;\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("    flex:0 0 auto;\r\n");
      out.write("  }\r\n");
      out.write("  .cs-fab__label{\r\n");
      out.write("    color:#fff;\r\n");
      out.write("    font-weight:900;\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("    letter-spacing:-.2px;\r\n");
      out.write("    max-width:0;\r\n");
      out.write("    opacity:0;\r\n");
      out.write("    transform:translateX(6px);\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    white-space:nowrap;\r\n");
      out.write("    transition:max-width .22s ease, opacity .18s ease, transform .22s ease;\r\n");
      out.write("  }\r\n");
      out.write("  .cs-fab:hover{\r\n");
      out.write("    background:rgba(47,111,237,1);\r\n");
      out.write("    transform:translateY(-2px);\r\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.22);\r\n");
      out.write("  }\r\n");
      out.write("  .cs-fab:hover .cs-fab__label{\r\n");
      out.write("    max-width:140px;\r\n");
      out.write("    opacity:1;\r\n");
      out.write("    transform:translateX(0);\r\n");
      out.write("  }\r\n");
      out.write("  .cs-fab:focus-visible{\r\n");
      out.write("    outline:none;\r\n");
      out.write("    box-shadow:0 0 0 4px rgba(47,111,237,.25), 0 22px 50px rgba(0,0,0,.22);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  /* ===== 맨 위로 버튼 (고객센터 위에) ===== */\r\n");
      out.write("  .top-fab{\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    right:26px;\r\n");
      out.write("    bottom:92px; /* 고객센터 위 */\r\n");
      out.write("    z-index:9999;\r\n");
      out.write("    width:56px;\r\n");
      out.write("    height:56px;\r\n");
      out.write("    border-radius:999px;\r\n");
      out.write("    border:1px solid rgba(17,24,39,.10);\r\n");
      out.write("    background:#fff;\r\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.14);\r\n");
      out.write("    display:none; /* 스크롤 시 JS로 표시 */\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    -webkit-tap-highlight-color:transparent;\r\n");
      out.write("  }\r\n");
      out.write("  .top-fab:hover{\r\n");
      out.write("    transform:translateY(-2px);\r\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.18);\r\n");
      out.write("  }\r\n");
      out.write("  .top-fab svg{\r\n");
      out.write("    width:22px;\r\n");
      out.write("    height:22px;\r\n");
      out.write("    stroke:#2f6fed;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"ptf-footer\" role=\"contentinfo\">\r\n");
      out.write("\r\n");
      out.write("  <!-- 상단 포인트 라인 -->\r\n");
      out.write("  <div class=\"ptf-footer__topbar\"></div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 링크 메뉴 -->\r\n");
      out.write("  <nav class=\"ptf-footer__nav\">\r\n");
      out.write("    <div class=\"ptf-footer__nav-inner\">\r\n");
      out.write("      <div class=\"ptf-footer__nav-links\">\r\n");
      out.write("        <a href=\"#\" class=\"pt-highlight\">개인정보 취급방침</a>\r\n");
      out.write("        <a href=\"#\">이용약관</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <!-- 메인 정보(화살표 친 큰 박스) -->\r\n");
      out.write("  <div class=\"ptf-footer__body\">\r\n");
      out.write("    <div class=\"ptf-footer__body-inner\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ptf-footer__brand\">\r\n");
      out.write("        <div class=\"ptf-footer__brand-logo\">Plan<span>Trip</span></div>\r\n");
      out.write("        <p class=\"ptf-footer__brand-desc\">\r\n");
      out.write("          나만의 여행을 더 쉽게,<br>더 똑똑하게.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ptf-footer__info\">\r\n");
      out.write("        <div class=\"ptf-footer__info-row\">\r\n");
      out.write("          <span>프로젝트 : <strong>PlanTrip (교육용 팀 프로젝트)</strong></span>\r\n");
      out.write("          <span class=\"pt-sep\">|</span>\r\n");
      out.write("          <span>소속 : <strong>백석대학교</strong></span>\r\n");
      out.write("          <span class=\"pt-sep\">|</span>\r\n");
      out.write("          <span>전화번호 : <strong>1234 - 1234</strong></span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"ptf-footer__info-row\">\r\n");
      out.write("          <span>충청남도 천안시 동남구 백석대학로 1 &nbsp;백석대학교 (214호 강의실)</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"ptf-footer__contact-item\">\r\n");
      out.write("          <span class=\"pt-icon\">✉</span>\r\n");
      out.write("          <a href=\"mailto:plantrip.team@baekseok.ac.kr\">plantrip.team@baekseok.ac.kr</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ 동그라미 문구를 \"화살표 박스 안\" 맨 아래에 붙임 -->\r\n");
      out.write("    <div class=\"ptf-footer__bottombar\">\r\n");
      out.write("      <div class=\"ptf-footer__bottombar-inner\">\r\n");
      out.write("        <p class=\"ptf-footer__copy\">© <span id=\"ptFooterYear\"></span> PlanTrip. All Rights Reserved.</p>\r\n");
      out.write("        <p class=\"ptf-footer__note\">본 사이트는 교육용 프로젝트이며 실제 예약/결제 기능을 제공하지 않습니다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Floating: 맨 위로 / 고객센터 -->\r\n");
      out.write("<button class=\"top-fab\" type=\"button\" aria-label=\"맨 위로\">\r\n");
      out.write("  <svg viewBox=\"0 0 24 24\" fill=\"none\" aria-hidden=\"true\">\r\n");
      out.write("    <path d=\"M12 5l-7 7m7-7l7 7M12 5v14\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\r\n");
      out.write("  </svg>\r\n");
      out.write("</button>\r\n");
      out.write("\r\n");
      out.write("<a class=\"cs-fab\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/support\" aria-label=\"고객센터\">\r\n");
      out.write("  <span class=\"cs-fab__icon\" aria-hidden=\"true\">?</span>\r\n");
      out.write("  <span class=\"cs-fab__label\">고객센터</span>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  document.body.setAttribute('data-ctx', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/fabs.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  (function(){\r\n");
      out.write("    var el = document.getElementById('ptFooterYear');\r\n");
      out.write("    if(el) el.textContent = new Date().getFullYear();\r\n");
      out.write("  })();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- ✅ Toast UI : 전 페이지 공통 (로그인/저장/안내 메시지) -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/ui-toast.css\" />\r\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/ui-toast.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- ✅ Auth Modal (Login/Signup) : 전 페이지 공통 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/auth-modal.css\" />\r\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-modal.js\"></script>\r\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-guard.js\"></script>\r\n");
      out.write("<!-- auth-modal ê³µíµ include -->\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인 모달 -->\r\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-login\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authLoginTitle\" tabindex=\"-1\">\r\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ dialog 전체에 깔리는 물결 배경 -->\r\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"auth-wrap auth-wrap--split\">\r\n");
      out.write("      <div class=\"auth-left\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("          <div class=\"logo\">TP</div>\r\n");
      out.write("          <div class=\"title\" id=\"authLoginTitle\">로그인</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form class=\"form\" action=\"/members/login\" method=\"post\">\r\n");
      out.write("          <div class=\"label\">아이디</div>\r\n");
      out.write("          <input class=\"input\" name=\"id\" type=\"text\" placeholder=\"아이디\" required />\r\n");
      out.write("          <!-- ✅ 필드 옆 에러(레이아웃 고정용) -->\r\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"id\"></div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"label\">비밀번호</div>\r\n");
      out.write("          <div class=\"input-row\">\r\n");
      out.write("            <input class=\"input\" name=\"password\" type=\"password\" placeholder=\"비밀번호\" required />\r\n");
      out.write("            <button class=\"eye\" type=\"button\" aria-label=\"비밀번호 보기\" aria-pressed=\"false\">\r\n");
      out.write("  <!-- eye-open -->\r\n");
      out.write("  <svg class=\"eye-ic eye-ic--open\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("    <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8s8.2 3.4 9.8 8c-1.6 4.6-5.8 8-9.8 8s-8.2-3.4-9.8-8Z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\r\n");
      out.write("    <circle cx=\"12\" cy=\"12\" r=\"3.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>\r\n");
      out.write("  </svg>\r\n");
      out.write("\r\n");
      out.write("  <!-- eye-off -->\r\n");
      out.write("  <svg class=\"eye-ic eye-ic--off\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("    <path d=\"M3 3l18 18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\r\n");
      out.write("    <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8 2.2 0 4.4.9 6.2 2.3M21.8 12c-1.6 4.6-5.8 8-9.8 8-2.2 0-4.4-.9-6.2-2.3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\r\n");
      out.write("    <path d=\"M10.2 10.2A3.2 3.2 0 0 0 12 15.2c.5 0 1-.1 1.4-.3\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\r\n");
      out.write("  </svg>\r\n");
      out.write("</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- ✅ 필드 옆 에러(레이아웃 고정용) -->\r\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"password\"></div>\r\n");
      out.write("\r\n");
      out.write("          <div style=\"text-align:right; margin-top:-6px;\">\r\n");
      out.write("            <a class=\"underline small\" href=\"/members/find-password\" data-auth-switch=\"find\">비밀번호를 잊으셨나요?</a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- (예외 상황용) 공통 에러: 박스 없이 텍스트만 출력 -->\r\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\r\n");
      out.write("\r\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">로그인</button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"social-row\">\r\n");
      out.write("  			<a class=\"social-btn\"\r\n");
      out.write("     			href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/oauth2/authorization/google\">\r\n");
      out.write("    		<span class=\"social-icon\" aria-hidden=\"true\">\r\n");
      out.write("      			<span class=\"social-dot\"></span>\r\n");
      out.write("    </span>\r\n");
      out.write("    		<span class=\"social-text\">구글</span>\r\n");
      out.write("  </a>\r\n");
      out.write("\r\n");
      out.write("  <button class=\"social-btn\" type=\"button\">\r\n");
      out.write("    <span class=\"social-icon\" aria-hidden=\"true\">\r\n");
      out.write("      <span class=\"social-dot\"></span>\r\n");
      out.write("    </span>\r\n");
      out.write("    <span class=\"social-text\">페이스북</span>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("          <div class=\"auth-footer\">\r\n");
      out.write("            계정이 없으신가요?\r\n");
      out.write("            <a class=\"underline\" href=\"/members/register\" data-auth-switch=\"signup\"><b>회원가입</b></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- 회원가입 모달 -->\r\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-signup\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authSignupTitle\" tabindex=\"-1\">\r\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\r\n");
      out.write("\r\n");
      out.write("    <!-- dialog 전체에 깔리는 물결/물방울 배경 (회원가입은 CSS에서 “왼쪽” 앵커 처리됨) -->\r\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("    <!-- [수정] 회원가입은 폼이 오른쪽으로 가야 하므로 auth-wrap--swap 사용 -->\r\n");
      out.write("    <div class=\"auth-wrap auth-wrap--swap\">\r\n");
      out.write("      <div class=\"auth-left\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("          <div class=\"logo\">TP</div>\r\n");
      out.write("          <div class=\"title\" id=\"authSignupTitle\">회원가입</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form class=\"form\" action=\"/members/register\" method=\"post\">\r\n");
      out.write("          <!-- (예외 상황용) 공통 에러: 박스 없이 텍스트만 출력 -->\r\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"label\">이름</div>\r\n");
      out.write("          <input class=\"input\" name=\"mName\" type=\"text\" placeholder=\"이름\" required />\r\n");
      out.write("\r\n");
      out.write("          <div class=\"label\">아이디</div>\r\n");
      out.write("          <input class=\"input\" name=\"mId\" type=\"text\" placeholder=\"아이디\" required />\r\n");
      out.write("          <!-- ✅ 중복 아이디/형식 에러 -->\r\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"mId\"></div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"label\">이메일</div>\r\n");
      out.write("          <input class=\"input\" name=\"mEmail\" type=\"email\" placeholder=\"이메일\" required />\r\n");
      out.write("          <!-- ✅ 중복 이메일/형식 에러 -->\r\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"mEmail\"></div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"label\">비밀번호</div>\r\n");
      out.write("<div class=\"input-row\">\r\n");
      out.write("  <input class=\"input\" name=\"mPw\" type=\"password\" placeholder=\"비밀번호\" required />\r\n");
      out.write("\r\n");
      out.write("  <button class=\"eye\" type=\"button\" aria-label=\"비밀번호 보기\" aria-pressed=\"false\">\r\n");
      out.write("    <!-- eye-open -->\r\n");
      out.write("    <svg class=\"eye-ic eye-ic--open\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("      <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8s8.2 3.4 9.8 8c-1.6 4.6-5.8 8-9.8 8s-8.2-3.4-9.8-8Z\"\r\n");
      out.write("            fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\r\n");
      out.write("      <circle cx=\"12\" cy=\"12\" r=\"3.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"/>\r\n");
      out.write("    </svg>\r\n");
      out.write("\r\n");
      out.write("    <!-- eye-off -->\r\n");
      out.write("    <svg class=\"eye-ic eye-ic--off\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("      <path d=\"M3 3l18 18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\r\n");
      out.write("      <path d=\"M2.2 12c1.6-4.6 5.8-8 9.8-8 2.2 0 4.4.9 6.2 2.3M21.8 12c-1.6 4.6-5.8 8-9.8 8-2.2 0-4.4-.9-6.2-2.3\"\r\n");
      out.write("            fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linejoin=\"round\"/>\r\n");
      out.write("      <path d=\"M10.2 10.2A3.2 3.2 0 0 0 12 15.2c.5 0 1-.1 1.4-.3\"\r\n");
      out.write("            fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\"/>\r\n");
      out.write("    </svg>\r\n");
      out.write("  </button>\r\n");
      out.write("</div>\r\n");
      out.write("          <!-- ✅ 비밀번호 관련 에러(필요 시) -->\r\n");
      out.write("          <div class=\"field-error\" data-auth-field-error=\"mPw\"></div>\r\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">회원가입</button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"auth-footer\">\r\n");
      out.write("            이미 회원이신가요?\r\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>로그인</b></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- [수정] 오른쪽(또는 왼쪽) 빈 자리용: 배경은 wave-bg가 담당 -->\r\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<!-- 비밀번호 찾기(재설정 링크) 모달 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-find\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authFindTitle\" tabindex=\"-1\">\r\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\r\n");
      out.write("\r\n");
      out.write("    <!-- ✅ dialog 전체 물결 배경(센터 정렬 버전) -->\r\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"auth-wrap auth-wrap--center\">\r\n");
      out.write("      <div class=\"auth-left\">\r\n");
      out.write("        <div class=\"brand\">\r\n");
      out.write("          <div class=\"logo\">TP</div>\r\n");
      out.write("          <div class=\"title\" id=\"authFindTitle\">비밀번호 찾기</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form class=\"form\" action=\"/members/find-password\" method=\"post\" data-find-form>\r\n");
      out.write("          <div class=\"label\">가입 이메일</div>\r\n");
      out.write("          <input class=\"input\" name=\"email\" type=\"email\" placeholder=\"example@email.com\" required />\r\n");
      out.write("\r\n");
      out.write("          <div class=\"helper\">\r\n");
      out.write("            입력하신 이메일로 <b>비밀번호 재설정 링크</b>를 보내드립니다.<br/>\r\n");
      out.write("            링크는 일정 시간 후 만료됩니다.\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\r\n");
      out.write("\r\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">재설정 링크 받기</button>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"auth-footer\">\r\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>로그인으로</b></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"lr-modal\" id=\"loginRequiredModal\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"lr-backdrop\" data-lr-close></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"lr-dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"lrTitle\" tabindex=\"-1\">\r\n");
      out.write("    <div class=\"lr-icon\" aria-hidden=\"true\">🔒</div>\r\n");
      out.write("    <h2 class=\"lr-title\" id=\"lrTitle\">로그인이 필요한 작업입니다</h2>\r\n");
      out.write("    <p class=\"lr-desc\" id=\"lrDesc\">계속하려면 로그인해 주세요.</p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"lr-actions\">\r\n");
      out.write("      <button type=\"button\" class=\"lr-btn ghost\" data-lr-cancel>취소</button>\r\n");
      out.write("      <button type=\"button\" class=\"lr-btn solid\" data-lr-confirm>확인</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/members/mypage/plans.jsp(66,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:length(plans)}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/members/mypage/plans.jsp(72,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty plans}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <div style=\"padding: 60px 20px; text-align: center; color: #888;\">\r\n");
        out.write("            <svg width=\"48\" height=\"48\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"margin-bottom: 15px; opacity: 0.5;\">\r\n");
        out.write("              <path d=\"M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z\"></path>\r\n");
        out.write("              <circle cx=\"12\" cy=\"10\" r=\"3\"></circle>\r\n");
        out.write("            </svg>\r\n");
        out.write("            <p>아직 작성한 여행 계획이 없습니다.<br>새로운 여행을 계획해 보세요!</p>\r\n");
        out.write("          </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/members/mypage/plans.jsp(82,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty plans}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("          <table class=\"mp-table\" id=\"plansTable\">\r\n");
        out.write("            <thead>\r\n");
        out.write("              <tr>\r\n");
        out.write("                <th style=\"width: 80px;\">번호</th>\r\n");
        out.write("                <th>계획 제목</th>\r\n");
        out.write("                <th style=\"width: 140px;\">작성일</th>\r\n");
        out.write("                <th style=\"width: 200px;\">관리</th>\r\n");
        out.write("              </tr>\r\n");
        out.write("            </thead>\r\n");
        out.write("            <tbody>\r\n");
        out.write("              ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("            </tbody>\r\n");
        out.write("          </table>\r\n");
        out.write("\r\n");
        out.write("          <div class=\"mp-pagination\" id=\"plansPagination\" aria-label=\"페이지네이션\"></div>\r\n");
        out.write("          <script>\r\n");
        out.write("            (function(){\r\n");
        out.write("              const table = document.getElementById('plansTable');\r\n");
        out.write("              if(!table) return;\r\n");
        out.write("              const tbody = table.querySelector('tbody');\r\n");
        out.write("              if(!tbody) return;\r\n");
        out.write("              const rows = Array.from(tbody.querySelectorAll('tr'));\r\n");
        out.write("              const pager = document.getElementById('plansPagination');\r\n");
        out.write("              const pageSize = 10;\r\n");
        out.write("              const total = rows.length;\r\n");
        out.write("              const pages = Math.max(1, Math.ceil(total / pageSize));\r\n");
        out.write("              let current = 1;\r\n");
        out.write("\r\n");
        out.write("              function render(){\r\n");
        out.write("                rows.forEach((r, idx)=>{\r\n");
        out.write("                  const p = Math.floor(idx / pageSize) + 1;\r\n");
        out.write("                  r.style.display = (p === current) ? '' : 'none';\r\n");
        out.write("                });\r\n");
        out.write("                if(!pager) return;\r\n");
        out.write("                pager.innerHTML = '';\r\n");
        out.write("                if(pages <= 1) return; // 1페이지뿐이면 버튼 숨김\r\n");
        out.write("\r\n");
        out.write("                for(let p=1; p<=pages; p++){\r\n");
        out.write("                  const b = document.createElement('button');\r\n");
        out.write("                  b.type = 'button';\r\n");
        out.write("                  b.className = 'mp-page' + (p === current ? ' is-active' : '');\r\n");
        out.write("                  b.textContent = p;\r\n");
        out.write("                  b.addEventListener('click', ()=>{ current = p; render(); });\r\n");
        out.write("                  pager.appendChild(b);\r\n");
        out.write("                }\r\n");
        out.write("              }\r\n");
        out.write("              render();\r\n");
        out.write("            })();\r\n");
        out.write("          </script>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/views/members/mypage/plans.jsp(93,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("p");
    // /WEB-INF/views/members/mypage/plans.jsp(93,14) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/members/mypage/plans.jsp(93,14) '${plans}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${plans}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <tr>\r\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.no}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                  <td class=\"td-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                  <td style=\"color: #888;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.regDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("                  <td>\r\n");
          out.write("                    <div style=\"display: flex; gap: 8px; justify-content: center; align-items: center;\">\r\n");
          out.write("                        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/members/mypage/plans/view?pIdx=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pIdx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn-view\">상세보기</a>\r\n");
          out.write("                        <form action=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/members/mypage/plans/delete\" method=\"get\" style=\"margin: 0;\">\r\n");
          out.write("                            <input type=\"hidden\" name=\"pIdx\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.pIdx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                            <button type=\"submit\" class=\"btn-delete\" onclick=\"return confirm('정말 이 계획을 삭제하시겠습니까?');\">삭제</button>\r\n");
          out.write("                        </form>\r\n");
          out.write("                    </div>\r\n");
          out.write("                  </td>\r\n");
          out.write("                </tr>\r\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
