/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-03-01 12:52:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.spot;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class all_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/Users/ddd04/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jspf", Long.valueOf(1772369129938L));
    _jspx_dependants.put("/WEB-INF/views/common/findPasswordModal.jspf", Long.valueOf(1772369129934L));
    _jspx_dependants.put("/WEB-INF/views/common/loginRequiredModal.jspf", Long.valueOf(1772369129949L));
    _jspx_dependants.put("/WEB-INF/views/common/signupModal.jspf", Long.valueOf(1772369129952L));
    _jspx_dependants.put("file:/C:/Users/ddd04/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1767668479510L));
    _jspx_dependants.put("/WEB-INF/views/common/theme.jspf", Long.valueOf(1772369129956L));
    _jspx_dependants.put("/WEB-INF/views/common/authModal.jspf", Long.valueOf(1772369129929L));
    _jspx_dependants.put("/WEB-INF/views/common/loginModal.jspf", Long.valueOf(1772369129944L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fj_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fj_005fchoose.release();
    _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/theme-init.js\"></script>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" - 전체보기</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("    <script src=\"/js/theme.js\"></script>\r\n");
      out.write("    <script defer src=\"/js/nav-wave.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Pretendard', sans-serif; background-color: #f8f9fa; margin: 0; }\r\n");
      out.write("        .container { max-width: 1200px; margin: 0 auto; padding: 40px 20px; }\r\n");
      out.write("        \r\n");
      out.write("        /* 2단 레이아웃 설정 */\r\n");
      out.write("        .main-layout { display: flex; gap: 30px; align-items: flex-start; }\r\n");
      out.write("        \r\n");
      out.write("        /* 왼쪽 사이드바 스타일 */\r\n");
      out.write("        .sidebar { width: 240px; position: sticky; top: 92px; flex-shrink: 0; }\r\n");
      out.write("        .category-menu { background: white; border-radius: 16px; padding: 15px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); }\r\n");
      out.write("        .menu-title { font-size: 16px; font-weight: bold; color: #888; margin-bottom: 15px; padding-left: 10px; }\r\n");
      out.write("        .menu-list { list-style: none; padding: 0; margin: 0; }\r\n");
      out.write("        .menu-item a { \r\n");
      out.write("            display: block; padding: 12px 15px; text-decoration: none; color: #555; \r\n");
      out.write("            border-radius: 10px; margin-bottom: 5px; transition: 0.2s; font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item a:hover { background: #f0f4ff; color: #3264ff; }\r\n");
      out.write("        .menu-item.active a { background: #3264ff; color: white; font-weight: bold; }\r\n");
      out.write("\r\n");
      out.write("        /* 오른쪽 컨텐츠 영역 */\r\n");
      out.write("        .content-area { flex: 1; }\r\n");
      out.write("        .header-section { margin-bottom: 30px; }\r\n");
      out.write("        .category-title { font-size: 24px; font-weight: 800; color: #333; }\r\n");
      out.write("        .city-name { color: #3264ff; }\r\n");
      out.write("\r\n");
      out.write("        /* 리스트형 카드 디자인 */\r\n");
      out.write("        .spot-list { display: flex; flex-direction: column; gap: 20px; }\r\n");
      out.write("        .card { \r\n");
      out.write("            background: white; border-radius: 16px; overflow: hidden; \r\n");
      out.write("            box-shadow: 0 4px 15px rgba(0,0,0,0.05); transition: 0.3s;\r\n");
      out.write("            text-decoration: none; color: inherit; display: flex; height: 180px;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover { transform: translateY(-5px); box-shadow: 0 8px 25px rgba(0,0,0,0.1); }\r\n");
      out.write("        \r\n");
      out.write("        .img-box { width: 240px; background-color: #eee; background-size: cover; background-position: center; flex-shrink: 0; }\r\n");
      out.write("        \r\n");
      out.write("        .info-box { padding: 25px; flex: 1; display: flex; flex-direction: column; justify-content: center; position: relative; }\r\n");
      out.write("        .spot-title { font-size: 20px; font-weight: 700; margin-bottom: 8px; color: #333; }\r\n");
      out.write("        .spot-addr { font-size: 15px; color: #777; margin-bottom: 10px; }\r\n");
      out.write("		/* 기존 .spot-price는 파란색 유지 */\r\n");
      out.write("		.spot-price { \r\n");
      out.write("		    font-size: 16px; \r\n");
      out.write("		    color: #3264ff; \r\n");
      out.write("		    font-weight: bold; \r\n");
      out.write("		    display: flex; \r\n");
      out.write("		    align-items: center; \r\n");
      out.write("		    gap: 4px; /* 별과 숫자 사이 간격 */\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		/* 추가: 별 아이콘만 노란색으로 설정 */\r\n");
      out.write("		.star-yellow {\r\n");
      out.write("		    color: #ffc107; /* 노란색/금색 */\r\n");
      out.write("		    font-size: 18px; /* 별 크기 살짝 조정 (취향껏) */\r\n");
      out.write("		}\r\n");
      out.write("        \r\n");
      out.write("        .btn-detail { \r\n");
      out.write("            position: absolute; right: 25px; bottom: 25px;\r\n");
      out.write("            background: #f0f4ff; color: #3264ff; padding: 8px 18px; \r\n");
      out.write("            border-radius: 8px; font-size: 14px; font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<header style=\"background: white; border-bottom: 1px solid #f0f0f0; padding: 12px 0; position: sticky; top: 0; z-index: 1000; box-shadow: 0 2px 10px rgba(0,0,0,0.02);\">\r\n");
      out.write("		    <div style=\"max-width: 1200px; margin: 0 auto; padding: 0 20px; display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("		        \r\n");
      out.write("		        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\" style=\"text-decoration: none; display: flex; align-items: center;\">\r\n");
      out.write("		            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/PlanTriplog.png\" \r\n");
      out.write("		                 alt=\"PlanTrip 로고\" \r\n");
      out.write("		                 style=\"height: 45px; width: auto; object-fit: contain;\">\r\n");
      out.write("		        </a>\r\n");
      out.write("\r\n");
      out.write("		        <nav style=\"display: flex; gap: 20px; font-size: 15px; font-weight: 600;\">\r\n");
      out.write("		            </nav>\r\n");
      out.write("		        \r\n");
      out.write("		    </div>\r\n");
      out.write("		</header>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"main-layout\">\r\n");
      out.write("        \r\n");
      out.write("        <aside class=\"sidebar\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/spots/spot?cityId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("               style=\"text-decoration: none; color: #888; font-size: 14px; display: inline-block; margin-bottom: 20px; font-weight: bold;\">\r\n");
      out.write("               &lt; 메인으로 돌아가기\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"category-menu\">\r\n");
      out.write("                <div class=\"menu-title\">카테고리</div>\r\n");
      out.write("                <ul class=\"menu-list\">\r\n");
      out.write("                    <li class=\"menu-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'TOUR' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <a href=\"?cityId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&catCode=TOUR\">🏛️ 인기 관광지</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'STAY' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <a href=\"?cityId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&catCode=STAY\">🛌 추천 숙소</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'ACT' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <a href=\"?cityId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&catCode=ACT\">🏄 문화/액티비티</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"menu-item ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'FOOD' ? 'active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        <a href=\"?cityId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&catCode=FOOD\">🍱 추천 맛집</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </aside>\r\n");
      out.write("\r\n");
      out.write("        <main class=\"content-area\">\r\n");
      out.write("            <div class=\"header-section\">\r\n");
      out.write("                <div class=\"category-title\">\r\n");
      out.write("                    <span class=\"city-name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${city.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> \r\n");
      out.write("                    ");
      if (_jspx_meth_j_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"color: #999; margin-top: 5px;\">총 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${spotList.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("개의 장소가 검색되었습니다.</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"spot-list\">\r\n");
      out.write("			    ");
      if (_jspx_meth_j_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("            \r\n");
      out.write("            ");
      if (_jspx_meth_j_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </main>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<style>\n");
      out.write("  .ptf-footer{\n");
      out.write("    background:#fff;\n");
      out.write("    color:#111827;\n");
      out.write("    position:relative;\n");
      out.write("    z-index:10;\n");
      out.write("    margin-top:0;\n");
      out.write("    /* â ì ì²´ íì´ì§ ê³µíµ footer: ê°ë¡ ì¤í¬ë¡¤(100vw) ë°©ì§ */\n");
      out.write("    width:100%;\n");
      out.write("    margin-left:0;\n");
      out.write("    box-sizing:border-box;\n");
      out.write("    overflow-x:hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("  /* ìë¨ íë í¬ì¸í¸ ë¼ì¸(ê·¸ëë¡ ì ì§) */\n");
      out.write("  .ptf-footer__topbar{\n");
      out.write("    height:3px;\n");
      out.write("    background: linear-gradient(90deg,#2f6fed 0%, #5b8cff 50%, #2f6fed 100%);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ë§í¬ ë©ë´ ìì­(ê·¸ëë¡ ì ì§) */\n");
      out.write("  .ptf-footer__nav{\n");
      out.write("    border-bottom:1px solid #e5e7eb;\n");
      out.write("    padding:14px 0;\n");
      out.write("    background:#fff;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px;\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:space-between;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("    gap:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links a{\n");
      out.write("    font-size:13px;\n");
      out.write("    font-weight:600;\n");
      out.write("    color:#374151;\n");
      out.write("    text-decoration:none;\n");
      out.write("    padding:4px 14px;\n");
      out.write("    border-right:1px solid #d1d5db;\n");
      out.write("    transition:color .15s;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links a:first-child{ padding-left:0; }\n");
      out.write("  .ptf-footer__nav-links a:last-child{ border-right:none; }\n");
      out.write("  .ptf-footer__nav-links a:hover{ color:#2f6fed; }\n");
      out.write("  .ptf-footer__nav-links a.pt-highlight{\n");
      out.write("    color:#2f6fed;\n");
      out.write("    font-weight:800;\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" /* ========== ë©ì¸ ì ë³´ ìì­ (ë¡ê³  + íë¡ì í¸ ì ë³´) ========== */\n");
      out.write("  /* ë©ì¸ ì ë³´ ìì­(í° ë°ì¤) */\n");
      out.write("  .ptf-footer__body{\n");
      out.write("    padding:32px 0 0;              /* â ìëë bottombarê° ë°ë¡ ìì¼ë 0 */\n");
      out.write("    border-bottom:1px solid #e5e7eb;\n");
      out.write("    background:#fff;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__body-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px 22px;           /* â ë°ì¤ ì ë´ì© ìë ì¬ë°± */\n");
      out.write("    display:grid;\n");
      out.write("    grid-template-columns:220px 1fr;\n");
      out.write("    gap:48px;\n");
      out.write("    align-items:start;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .ptf-footer__brand-logo{\n");
      out.write("    font-size:24px;\n");
      out.write("    font-weight:900;\n");
      out.write("    color:#111827;\n");
      out.write("    letter-spacing:-.3px;\n");
      out.write("    margin-bottom:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__brand-logo span{ color:#2f6fed; }\n");
      out.write("\n");
      out.write("/* ---- ì¼ìª½: ë¸ëë ì¤ëª íì¤í¸ ---- */\n");
      out.write("  .ptf-footer__brand-desc{\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#6b7280;\n");
      out.write("    line-height:1.6;\n");
      out.write("    margin:0;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("/* ---- ì¤ë¥¸ìª½: íë¡ì í¸ ì ë³´ ìì­ ---- */\n");
      out.write("  .ptf-footer__info{\n");
      out.write("    display:flex;\n");
      out.write("    flex-direction:column;\n");
      out.write("    gap:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__info-row{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("    gap:6px 20px;\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#374151;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__info-row .pt-sep{ color:#d1d5db; }\n");
      out.write("  .ptf-footer__info-row strong{ font-weight:700; color:#111827; }\n");
      out.write("\n");
      out.write("  .ptf-footer__contact-item{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    gap:6px;\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#374151;\n");
      out.write("    margin-top:4px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__contact-item a{\n");
      out.write("    color:#374151;\n");
      out.write("    text-decoration:underline;\n");
      out.write("    text-underline-offset:3px;\n");
      out.write("    transition:color .15s;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__contact-item a:hover{ color:#2f6fed; }\n");
      out.write("  .ptf-footer__contact-item .pt-icon{\n");
      out.write("    width:18px;\n");
      out.write("    height:18px;\n");
      out.write("    background:#f3f4f6;\n");
      out.write("    border-radius:50%;\n");
      out.write("    display:inline-flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:center;\n");
      out.write("    font-size:10px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* â ëê·¸ë¼ë¯¸ ë¬¸êµ¬ë¥¼ \"íì´í ë°ì¤ ì\"ì ë¶ì´ë íë¨ ë° */\n");
      out.write("  .ptf-footer__bottombar{\n");
      out.write("    background:#f3f4f6;                 /* â íì(ì°í) ë°°ê²½ì¼ë¡ 'ë¶ì´' ë³´ì´ê² */\n");
      out.write("    border-top:1px solid #e5e7eb;       /* â ë°ì¤ ììì ë± ë¶ë êµ¬ë¶ì  */\n");
      out.write("    padding:12px 0;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__bottombar-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px;\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:space-between;      /* â ì¢/ì° */\n");
      out.write("    gap:16px;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__copy,\n");
      out.write("  .ptf-footer__note{\n");
      out.write("    margin:0;\n");
      out.write("    font-size:13px;\n");
      out.write("    line-height:1.5;\n");
      out.write("    color:rgba(17,24,39,.70);\n");
      out.write("  }\n");
      out.write("  .ptf-footer__note{ text-align:right; }\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("  @media (max-width:860px){\n");
      out.write("    .ptf-footer__body-inner{ grid-template-columns:1fr; gap:24px; }\n");
      out.write("    .ptf-footer__nav-links a{ font-size:12px; padding:4px 10px; }\n");
      out.write("  }\n");
      out.write("  @media (max-width:768px){\n");
      out.write("    .ptf-footer__bottombar-inner{\n");
      out.write("      flex-direction:column;\n");
      out.write("      align-items:flex-start;\n");
      out.write("    }\n");
      out.write("    .ptf-footer__note{ text-align:left; }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ===== Floating ê³ ê°ì¼í° (ê¸°ì¡´ UI ê·¸ëë¡) ===== */\n");
      out.write("  .cs-fab{\n");
      out.write("    position:fixed;\n");
      out.write("    right:26px;\n");
      out.write("    bottom:26px;\n");
      out.write("    z-index:9999;\n");
      out.write("    height:56px;\n");
      out.write("    min-width:78px;\n");
      out.write("    padding:10px 14px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    background:rgba(47,111,237,.92);\n");
      out.write("    backdrop-filter:blur(6px);\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.18);\n");
      out.write("    display:inline-flex;\n");
      out.write("    align-items:center;\n");
      out.write("    gap:10px;\n");
      out.write("    border:1px solid rgba(255,255,255,.18);\n");
      out.write("    user-select:none;\n");
      out.write("    -webkit-tap-highlight-color:transparent;\n");
      out.write("    text-decoration:none;\n");
      out.write("  }\n");
      out.write("  .cs-fab__icon{\n");
      out.write("    width:38px;\n");
      out.write("    height:38px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    background:#fff;\n");
      out.write("    color:#2f6fed;\n");
      out.write("    display:grid;\n");
      out.write("    place-items:center;\n");
      out.write("    font-weight:900;\n");
      out.write("    font-size:18px;\n");
      out.write("    flex:0 0 auto;\n");
      out.write("  }\n");
      out.write("  .cs-fab__label{\n");
      out.write("    color:#fff;\n");
      out.write("    font-weight:900;\n");
      out.write("    font-size:14px;\n");
      out.write("    letter-spacing:-.2px;\n");
      out.write("    max-width:0;\n");
      out.write("    opacity:0;\n");
      out.write("    transform:translateX(6px);\n");
      out.write("    overflow:hidden;\n");
      out.write("    white-space:nowrap;\n");
      out.write("    transition:max-width .22s ease, opacity .18s ease, transform .22s ease;\n");
      out.write("  }\n");
      out.write("  .cs-fab:hover{\n");
      out.write("    background:rgba(47,111,237,1);\n");
      out.write("    transform:translateY(-2px);\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.22);\n");
      out.write("  }\n");
      out.write("  .cs-fab:hover .cs-fab__label{\n");
      out.write("    max-width:140px;\n");
      out.write("    opacity:1;\n");
      out.write("    transform:translateX(0);\n");
      out.write("  }\n");
      out.write("  .cs-fab:focus-visible{\n");
      out.write("    outline:none;\n");
      out.write("    box-shadow:0 0 0 4px rgba(47,111,237,.25), 0 22px 50px rgba(0,0,0,.22);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ===== ë§¨ ìë¡ ë²í¼ (ê³ ê°ì¼í° ìì) ===== */\n");
      out.write("  .top-fab{\n");
      out.write("    position:fixed;\n");
      out.write("    right:26px;\n");
      out.write("    bottom:92px; /* ê³ ê°ì¼í° ì */\n");
      out.write("    z-index:9999;\n");
      out.write("    width:56px;\n");
      out.write("    height:56px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    border:1px solid rgba(17,24,39,.10);\n");
      out.write("    background:#fff;\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.14);\n");
      out.write("    display:none; /* ì¤í¬ë¡¤ ì JSë¡ íì */\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:center;\n");
      out.write("    cursor:pointer;\n");
      out.write("    -webkit-tap-highlight-color:transparent;\n");
      out.write("  }\n");
      out.write("  .top-fab:hover{\n");
      out.write("    transform:translateY(-2px);\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.18);\n");
      out.write("  }\n");
      out.write("  .top-fab svg{\n");
      out.write("    width:22px;\n");
      out.write("    height:22px;\n");
      out.write("    stroke:#2f6fed;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<footer class=\"ptf-footer\" role=\"contentinfo\">\n");
      out.write("\n");
      out.write("  <!-- ìë¨ í¬ì¸í¸ ë¼ì¸ -->\n");
      out.write("  <div class=\"ptf-footer__topbar\"></div>\n");
      out.write("\n");
      out.write("  <!-- ë§í¬ ë©ë´ -->\n");
      out.write("  <nav class=\"ptf-footer__nav\">\n");
      out.write("    <div class=\"ptf-footer__nav-inner\">\n");
      out.write("      <div class=\"ptf-footer__nav-links\">\n");
      out.write("        <a href=\"#\" class=\"pt-highlight\">ê°ì¸ì ë³´ ì·¨ê¸ë°©ì¹¨</a>\n");
      out.write("        <a href=\"#\">ì´ì©ì½ê´</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <!-- ë©ì¸ ì ë³´(íì´í ì¹ í° ë°ì¤) -->\n");
      out.write("  <div class=\"ptf-footer__body\">\n");
      out.write("    <div class=\"ptf-footer__body-inner\">\n");
      out.write("\n");
      out.write("      <div class=\"ptf-footer__brand\">\n");
      out.write("        <div class=\"ptf-footer__brand-logo\">Plan<span>Trip</span></div>\n");
      out.write("        <p class=\"ptf-footer__brand-desc\">\n");
      out.write("          ëë§ì ì¬íì ë ì½ê²,<br>ë ëëíê².\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"ptf-footer__info\">\n");
      out.write("        <div class=\"ptf-footer__info-row\">\n");
      out.write("          <span>íë¡ì í¸ : <strong>PlanTrip (êµì¡ì© í íë¡ì í¸)</strong></span>\n");
      out.write("          <span class=\"pt-sep\">|</span>\n");
      out.write("          <span>ìì : <strong>ë°±ìëíêµ</strong></span>\n");
      out.write("          <span class=\"pt-sep\">|</span>\n");
      out.write("          <span>ê°ìì¤ : <strong>214í¸</strong></span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"ptf-footer__info-row\">\n");
      out.write("          <span>ì¶©ì²­ë¨ë ì²ìì ëë¨êµ¬ ë°±ìëíë¡ 1 &nbsp;ë°±ìëíêµ (214í¸ ê°ìì¤)</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"ptf-footer__contact-item\">\n");
      out.write("          <span class=\"pt-icon\">â</span>\n");
      out.write("          <a href=\"mailto:plantrip.team@baekseok.ac.kr\">plantrip.team@baekseok.ac.kr</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- â ëê·¸ë¼ë¯¸ ë¬¸êµ¬ë¥¼ \"íì´í ë°ì¤ ì\" ë§¨ ìëì ë¶ì -->\n");
      out.write("    <div class=\"ptf-footer__bottombar\">\n");
      out.write("      <div class=\"ptf-footer__bottombar-inner\">\n");
      out.write("        <p class=\"ptf-footer__copy\">Â© <span id=\"ptFooterYear\"></span> PlanTrip. All Rights Reserved.</p>\n");
      out.write("        <p class=\"ptf-footer__note\">ë³¸ ì¬ì´í¸ë êµì¡ì© íë¡ì í¸ì´ë©° ì¤ì  ìì½/ê²°ì  ê¸°ë¥ì ì ê³µíì§ ììµëë¤.</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Floating: ë§¨ ìë¡ / ê³ ê°ì¼í° -->\n");
      out.write("<button class=\"top-fab\" type=\"button\" aria-label=\"ë§¨ ìë¡\">\n");
      out.write("  <svg viewBox=\"0 0 24 24\" fill=\"none\" aria-hidden=\"true\">\n");
      out.write("    <path d=\"M12 5l-7 7m7-7l7 7M12 5v14\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\n");
      out.write("  </svg>\n");
      out.write("</button>\n");
      out.write("\n");
      out.write("<a class=\"cs-fab\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/support\" aria-label=\"ê³ ê°ì¼í°\">\n");
      out.write("  <span class=\"cs-fab__icon\" aria-hidden=\"true\">?</span>\n");
      out.write("  <span class=\"cs-fab__label\">ê³ ê°ì¼í°</span>\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  document.body.setAttribute('data-ctx', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/fabs.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  (function(){\n");
      out.write("    var el = document.getElementById('ptFooterYear');\n");
      out.write("    if(el) el.textContent = new Date().getFullYear();\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- â Toast UI : ì  íì´ì§ ê³µíµ (ë¡ê·¸ì¸/ì ì¥/ìë´ ë©ìì§) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/ui-toast.css\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/ui-toast.js\"></script>\n");
      out.write("\n");
      out.write("<!-- â Auth Modal (Login/Signup) : ì  íì´ì§ ê³µíµ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/auth-modal.css\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-modal.js\"></script>\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-guard.js\"></script>\n");
      out.write("<!-- auth-modal ê³µíµ include -->\n");
      out.write("<!-- ë¡ê·¸ì¸ ëª¨ë¬ -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-login\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authLoginTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"ë«ê¸°\">â</button>\n");
      out.write("\n");
      out.write("    <!-- â dialog ì ì²´ì ê¹ë¦¬ë ë¬¼ê²° ë°°ê²½ -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-wrap auth-wrap--split\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authLoginTitle\">ë¡ê·¸ì¸</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/login\" method=\"post\">\n");
      out.write("          <div class=\"label\">ìì´ë</div>\n");
      out.write("          <input class=\"input\" name=\"id\" type=\"text\" placeholder=\"ìì´ë\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">ë¹ë°ë²í¸</div>\n");
      out.write("          <div class=\"input-row\">\n");
      out.write("            <input class=\"input\" name=\"password\" type=\"password\" placeholder=\"ë¹ë°ë²í¸\" required />\n");
      out.write("            <span class=\"eye\" role=\"button\" tabindex=\"0\" aria-label=\"ë¹ë°ë²í¸ ë³´ê¸°\">ð</span>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div style=\"text-align:right; margin-top:-6px;\">\n");
      out.write("            <a class=\"underline small\" href=\"/members/find-password\" data-auth-switch=\"find\">ë¹ë°ë²í¸ë¥¼ ìì¼ì¨ëì?</a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">ë¡ê·¸ì¸</button>\n");
      out.write("\n");
      out.write("          <div class=\"social-row\">\n");
      out.write("            <button class=\"social-btn\" type=\"button\"><span class=\"social-dot\"></span> êµ¬ê¸</button>\n");
      out.write("            <button class=\"social-btn\" type=\"button\"><span class=\"social-dot\"></span> íì´ì¤ë¶</button>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            ê³ì ì´ ìì¼ì ê°ì?\n");
      out.write("            <a class=\"underline\" href=\"/members/register\" data-auth-switch=\"signup\"><b>íìê°ì</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("<!-- íìê°ì ëª¨ë¬ -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-signup\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authSignupTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"ë«ê¸°\">â</button>\n");
      out.write("\n");
      out.write("    <!-- dialog ì ì²´ì ê¹ë¦¬ë ë¬¼ê²°/ë¬¼ë°©ì¸ ë°°ê²½ (íìê°ìì CSSìì âì¼ìª½â ìµì»¤ ì²ë¦¬ë¨) -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <!-- [ìì ] íìê°ìì í¼ì´ ì¤ë¥¸ìª½ì¼ë¡ ê°ì¼ íë¯ë¡ auth-wrap--swap ì¬ì© -->\n");
      out.write("    <div class=\"auth-wrap auth-wrap--swap\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authSignupTitle\">íìê°ì</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/register\" method=\"post\">\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <div class=\"label\">ì´ë¦</div>\n");
      out.write("          <input class=\"input\" name=\"mName\" type=\"text\" placeholder=\"ì´ë¦\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">ìì´ë</div>\n");
      out.write("          <input class=\"input\" name=\"mId\" type=\"text\" placeholder=\"ìì´ë\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">ì´ë©ì¼</div>\n");
      out.write("          <input class=\"input\" name=\"mEmail\" type=\"email\" placeholder=\"ì´ë©ì¼\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">ë¹ë°ë²í¸</div>\n");
      out.write("          <div class=\"input-row\">\n");
      out.write("            <input class=\"input\" name=\"mPw\" type=\"password\" placeholder=\"ë¹ë°ë²í¸\" required />\n");
      out.write("            <span class=\"eye\" role=\"button\" tabindex=\"0\" aria-label=\"ë¹ë°ë²í¸ ë³´ê¸°\">ð</span>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">íìê°ì</button>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            ì´ë¯¸ íìì´ì ê°ì?\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>ë¡ê·¸ì¸</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- [ìì ] ì¤ë¥¸ìª½(ëë ì¼ìª½) ë¹ ìë¦¬ì©: ë°°ê²½ì wave-bgê° ë´ë¹ -->\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("<!-- ë¹ë°ë²í¸ ì°¾ê¸°(ì¬ì¤ì  ë§í¬) ëª¨ë¬ -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-find\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authFindTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"ë«ê¸°\">â</button>\n");
      out.write("\n");
      out.write("    <!-- â dialog ì ì²´ ë¬¼ê²° ë°°ê²½(ì¼í° ì ë ¬ ë²ì ) -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-wrap auth-wrap--center\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authFindTitle\">ë¹ë°ë²í¸ ì°¾ê¸°</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/find-password\" method=\"post\" data-find-form>\n");
      out.write("          <div class=\"label\">ê°ì ì´ë©ì¼</div>\n");
      out.write("          <input class=\"input\" name=\"email\" type=\"email\" placeholder=\"example@email.com\" required />\n");
      out.write("\n");
      out.write("          <div class=\"helper\">\n");
      out.write("            ìë ¥íì  ì´ë©ì¼ë¡ <b>ë¹ë°ë²í¸ ì¬ì¤ì  ë§í¬</b>ë¥¼ ë³´ë´ëë¦½ëë¤.<br/>\n");
      out.write("            ë§í¬ë ì¼ì  ìê° í ë§ë£ë©ëë¤.\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">ì¬ì¤ì  ë§í¬ ë°ê¸°</button>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>ë¡ê·¸ì¸ì¼ë¡</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("<div class=\"lr-modal\" id=\"loginRequiredModal\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"lr-backdrop\" data-lr-close></div>\n");
      out.write("\n");
      out.write("  <div class=\"lr-dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"lrTitle\" tabindex=\"-1\">\n");
      out.write("    <div class=\"lr-icon\" aria-hidden=\"true\">ð</div>\n");
      out.write("    <h2 class=\"lr-title\" id=\"lrTitle\">ë¡ê·¸ì¸ì´ íìí ìììëë¤</h2>\n");
      out.write("    <p class=\"lr-desc\" id=\"lrDesc\">ê³ìíë ¤ë©´ ë¡ê·¸ì¸í´ ì£¼ì¸ì.</p>\n");
      out.write("\n");
      out.write("    <div class=\"lr-actions\">\n");
      out.write("      <button type=\"button\" class=\"lr-btn ghost\" data-lr-cancel>ì·¨ì</button>\n");
      out.write("      <button type=\"button\" class=\"lr-btn solid\" data-lr-confirm>íì¸</button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("	// 하트 토글 통신 함수\r\n");
      out.write("	function toggleWish(event, sIdx, btn) {\r\n");
      out.write("	    event.preventDefault();\r\n");
      out.write("	    event.stopPropagation(); // 카드 링크로 이동하는 것을 방지하고 하트만 토글시킴\r\n");
      out.write("	    \r\n");
      out.write("	    fetch('/api/wish/toggle', {\r\n");
      out.write("	        method: 'POST',\r\n");
      out.write("	        headers: { 'Content-Type': 'application/json' },\r\n");
      out.write("	        body: JSON.stringify({ sIdx: sIdx })\r\n");
      out.write("	    })\r\n");
      out.write("	    .then(response => {\r\n");
      out.write("	        if (response.status === 401) {\r\n");
      out.write("	            alert('로그인이 필요한 서비스입니다.');\r\n");
      out.write("	            return;\r\n");
      out.write("	        }\r\n");
      out.write("	        return response.json();\r\n");
      out.write("	    })\r\n");
      out.write("	    .then(data => {\r\n");
      out.write("	        if (data && data.success) {\r\n");
      out.write("	            btn.innerText = data.isHearted ? '❤️' : '🤍';\r\n");
      out.write("	            if (data.isHearted) btn.classList.add('active');\r\n");
      out.write("	            else btn.classList.remove('active');\r\n");
      out.write("	        }\r\n");
      out.write("	    })\r\n");
      out.write("	    .catch(error => {\r\n");
      out.write("	        console.error('Error:', error);\r\n");
      out.write("	        alert('처리 중 오류가 발생했습니다.');\r\n");
      out.write("	    });\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_j_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_j_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fj_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_j_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_j_005fchoose_005f0.setParent(null);
    int _jspx_eval_j_005fchoose_005f0 = _jspx_th_j_005fchoose_005f0.doStartTag();
    if (_jspx_eval_j_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                        ");
        if (_jspx_meth_j_005fwhen_005f0(_jspx_th_j_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        ");
        if (_jspx_meth_j_005fwhen_005f1(_jspx_th_j_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        ");
        if (_jspx_meth_j_005fwhen_005f2(_jspx_th_j_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                        ");
        if (_jspx_meth_j_005fwhen_005f3(_jspx_th_j_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_j_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fchoose.reuse(_jspx_th_j_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_j_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_j_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_j_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_j_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fchoose_005f0);
    // /WEB-INF/views/spot/all.jsp(123,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'TOUR'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fwhen_005f0 = _jspx_th_j_005fwhen_005f0.doStartTag();
    if (_jspx_eval_j_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("인기 관광지");
        int evalDoAfterBody = _jspx_th_j_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.reuse(_jspx_th_j_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_j_005fwhen_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_j_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_j_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_j_005fwhen_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fchoose_005f0);
    // /WEB-INF/views/spot/all.jsp(124,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'STAY'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fwhen_005f1 = _jspx_th_j_005fwhen_005f1.doStartTag();
    if (_jspx_eval_j_005fwhen_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("추천 숙소");
        int evalDoAfterBody = _jspx_th_j_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fwhen_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.reuse(_jspx_th_j_005fwhen_005f1);
    return false;
  }

  private boolean _jspx_meth_j_005fwhen_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_j_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_j_005fwhen_005f2.setPageContext(_jspx_page_context);
    _jspx_th_j_005fwhen_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fchoose_005f0);
    // /WEB-INF/views/spot/all.jsp(125,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'ACT'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fwhen_005f2 = _jspx_th_j_005fwhen_005f2.doStartTag();
    if (_jspx_eval_j_005fwhen_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("문화/액티비티");
        int evalDoAfterBody = _jspx_th_j_005fwhen_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fwhen_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.reuse(_jspx_th_j_005fwhen_005f2);
    return false;
  }

  private boolean _jspx_meth_j_005fwhen_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_j_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_j_005fwhen_005f3.setPageContext(_jspx_page_context);
    _jspx_th_j_005fwhen_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fchoose_005f0);
    // /WEB-INF/views/spot/all.jsp(126,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${catCode eq 'FOOD'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fwhen_005f3 = _jspx_th_j_005fwhen_005f3.doStartTag();
    if (_jspx_eval_j_005fwhen_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("추천 맛집");
        int evalDoAfterBody = _jspx_th_j_005fwhen_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fwhen_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fwhen_0026_005ftest.reuse(_jspx_th_j_005fwhen_005f3);
    return false;
  }

  private boolean _jspx_meth_j_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_j_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_j_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_j_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/spot/all.jsp(133,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f0.setVar("s");
    // /WEB-INF/views/spot/all.jsp(133,7) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/spot/all.jsp(133,7) '${spotList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${spotList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_j_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_j_005fforEach_005f0 = _jspx_th_j_005fforEach_005f0.doStartTag();
      if (_jspx_eval_j_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			        <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/spots/detail/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"card\" style=\"position: relative;\">\r\n");
          out.write("			            <button class=\"wish-btn\" onclick=\"toggleWish(event, ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(", this)\" \r\n");
          out.write("			                    style=\"position: absolute; top: 15px; left: 15px; z-index: 10; background: rgba(255,255,255,0.9); border: none; border-radius: 50%; width: 35px; height: 35px; cursor: pointer; display: flex; align-items: center; justify-content: center; font-size: 18px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);\">\r\n");
          out.write("			                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.isHearted ? '❤️' : '🤍'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("			            </button>\r\n");
          out.write("			            <div class=\"img-box\" style=\"background-image: url('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/img/hero.jpg');\"></div>\r\n");
          out.write("			            <div class=\"info-box\">\r\n");
          out.write("			                <div class=\"spot-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("			                <div class=\"spot-addr\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.addr}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("			                <div class=\"spot-price\">\r\n");
          out.write("			                    <span class=\"star-yellow\">★</span> \r\n");
          out.write("			                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty s.price ? s.price : '0.0'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("			                </div>\r\n");
          out.write("			                <div class=\"btn-detail\">상세보기</div>\r\n");
          out.write("			            </div>\r\n");
          out.write("			        </a>\r\n");
          out.write("			    ");
          int evalDoAfterBody = _jspx_th_j_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_j_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_j_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_j_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_j_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_j_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f0.setParent(null);
    // /WEB-INF/views/spot/all.jsp(153,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty spotList}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f0 = _jspx_th_j_005fif_005f0.doStartTag();
    if (_jspx_eval_j_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                <div style=\"text-align: center; padding: 100px 0; color: #999; background: white; border-radius: 16px;\">\r\n");
        out.write("                    등록된 장소가 없습니다.\r\n");
        out.write("                </div>\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_j_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f0);
    return false;
  }
}
