/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.50
 * Generated at: 2026-03-02 08:08:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.transport;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class flight_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/Users/ddd04/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jspf", Long.valueOf(1772356936000L));
    _jspx_dependants.put("/WEB-INF/views/common/findPasswordModal.jspf", Long.valueOf(1772356488000L));
    _jspx_dependants.put("/WEB-INF/views/common/loginRequiredModal.jspf", Long.valueOf(1772356488000L));
    _jspx_dependants.put("/WEB-INF/views/common/signupModal.jspf", Long.valueOf(1772356488000L));
    _jspx_dependants.put("file:/C:/Users/ddd04/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1767668479510L));
    _jspx_dependants.put("/WEB-INF/views/common/theme.jspf", Long.valueOf(1772356488000L));
    _jspx_dependants.put("/WEB-INF/views/common/authModal.jspf", Long.valueOf(1772356488000L));
    _jspx_dependants.put("/WEB-INF/views/common/loginModal.jspf", Long.valueOf(1772356488000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("<script src=\"/js/theme-init.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n");
      out.write("  <title>항공권 시간 조회</title>\n");
      out.write("\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/header.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"/css/transport.css\" />\n");
      out.write("  <script defer src=\"/js/nav-wave.js\"></script>\n");
      out.write("  <script defer src=\"/js/transport.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"page-solid tp-page\" data-tp-mode=\"flight\">\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"tp-wrap\">\n");
      out.write("    <div class=\"tp-breadcrumb\">\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">메인</a>\n");
      out.write("      <span>›</span>\n");
      out.write("      <span>교통수단</span>\n");
      out.write("      <span>›</span>\n");
      out.write("      <span>항공권</span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"tp-head\">\n");
      out.write("      <div>\n");
      out.write("        <h1 class=\"tp-title\">항공권 조회</h1>\n");
      out.write("        <p class=\"tp-sub\">제주 ↔ 국내 전 공항 운항편을 날짜 기준으로 확인할 수 있습니다.</p>\n");
      out.write("      </div>\n");
      out.write("</div>\n");
      out.write("<!-- 검색 -->\n");
      out.write("    <div class=\"tp-card\">\n");
      out.write("<div class=\"tp-tabs2\" role=\"tablist\" aria-label=\"교통수단\">\n");
      out.write("  <a class=\"tp-tab2 is-active\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/flight?depAirport=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depAirport}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&arrAirport=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arrAirport}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&depPlandTime=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><span class=\"tp-tab2__icon\"><svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M21 16v-2l-8-5V3.5a1.5 1.5 0 0 0-3 0V9L2 14v2l8-2.5V19l-2 1.5V22l3-1 3 1v-1.5L13 19v-5.5l8 2.5Z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linejoin=\"round\"/></svg></span><span class=\"tp-tab2__label\">항공권</span></a>\n");
      out.write("  <a class=\"tp-tab2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/expbus?depCity=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&arrCity=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arrCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&depPlandTime=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><span class=\"tp-tab2__icon\"><svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M6 3h12a2 2 0 0 1 2 2v11a3 3 0 0 1-3 3H7a3 3 0 0 1-3-3V5a2 2 0 0 1 2-2z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"/><path d=\"M4 10h16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"/><path d=\"M7.5 19.5v1.5M16.5 19.5v1.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><circle cx=\"8\" cy=\"16\" r=\"1\" fill=\"currentColor\"/><circle cx=\"16\" cy=\"16\" r=\"1\" fill=\"currentColor\"/></svg></span><span class=\"tp-tab2__label\">버스</span></a>\n");
      out.write("  <a class=\"tp-tab2\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/train?depCity=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&arrCity=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arrCity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&depPlandTime=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><span class=\"tp-tab2__icon\"><svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"M6 3h12a2 2 0 0 1 2 2v10a4 4 0 0 1-4 4H8a4 4 0 0 1-4-4V5a2 2 0 0 1 2-2z\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\"/><path d=\"M8 19l-2 2M16 19l2 2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><path d=\"M7 8h10M7 12h10\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"/><circle cx=\"9\" cy=\"16\" r=\"1\" fill=\"currentColor\"/><circle cx=\"15\" cy=\"16\" r=\"1\" fill=\"currentColor\"/></svg></span><span class=\"tp-tab2__label\">기차</span></a>\n");
      out.write("</div>\n");
      out.write("<div class=\"tp-body\">\n");
      out.write("        \n");
      out.write("        <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/transport/flight/search\">\n");
      out.write("          <div class=\"tp-form-panel\">\n");
      out.write("            <!-- 검색 바 (공통 UI) -->\n");
      out.write("            <div class=\"tp-searchbar tp-searchbar--flight\">\n");
      out.write("              <div class=\"tp-searchbar__loc\">\n");
      out.write("                <div class=\"tp-field\">\n");
      out.write("                  <div class=\"tp-field__label\">출발 공항</div>\n");
      out.write("                  <input class=\"tp-field__input\" type=\"text\" id=\"tpDepAirportText\" readonly />\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"button\" class=\"tp-swap-btn\" data-tp-swap-air aria-label=\"출발/도착 바꾸기\">⇄</button>\n");
      out.write("\n");
      out.write("                <div class=\"tp-field\">\n");
      out.write("                  <div class=\"tp-field__label\">도착 공항</div>\n");
      out.write("                  <input class=\"tp-field__input\" type=\"text\" id=\"tpArrAirportText\" readonly />\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"tp-searchbar__date\">\n");
      out.write("                <div class=\"tp-field\">\n");
      out.write("                  <div class=\"tp-field__label\">출발일</div>\n");
      out.write("                  <input id=\"depDate\" data-tp-date-text type=\"text\" readonly class=\"tp-input tp-input--bar\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTimeIso}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required data-tp-hidden=\"depPlandTime\" />\n");
      out.write("                  <input type=\"hidden\" name=\"depPlandTime\" id=\"depPlandTime\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"tp-searchbar__action\">\n");
      out.write("                <button class=\"tp-btn-primary\" type=\"submit\">검색</button>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"tp-help\">날짜/공항 변경 시 자동 조회됩니다.</div>\n");
      out.write("\n");
      out.write("            <div class=\"tp-grid\" style=\"margin-top:14px;\">\n");
      out.write("              <div class=\"tp-col-6\">\n");
      out.write("                <div class=\"tp-label\">출발 공항</div>\n");
      out.write("                <div class=\"tp-chip-row tp-chip-row-scroll\" data-tp-air-chips=\"depAirportId\">\n");
      out.write("                  <button type=\"button\"\n");
      out.write("                          class=\"tp-chip ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'NAARKPC' == (empty depAirportId ? 'NAARKPC' : depAirportId) ? 'is-active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("                          data-air-id=\"NAARKPC\">제주</button>\n");
      out.write("                  ");
      if (_jspx_meth_j_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"tp-col-6\">\n");
      out.write("                <div class=\"tp-label\">도착 공항</div>\n");
      out.write("                <div class=\"tp-chip-row tp-chip-row-scroll\" data-tp-air-chips=\"arrAirportId\">\n");
      out.write("                  <button type=\"button\"\n");
      out.write("                          class=\"tp-chip ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${'NAARKPC' == (empty arrAirportId ? selectedAirportId : arrAirportId) ? 'is-active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("                          data-air-id=\"NAARKPC\">제주</button>\n");
      out.write("                  ");
      if (_jspx_meth_j_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <input type=\"hidden\" name=\"depAirportId\" id=\"depAirportId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty depAirportId ? 'NAARKPC' : depAirportId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("            <input type=\"hidden\" name=\"arrAirportId\" id=\"arrAirportId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty arrAirportId ? selectedAirportId : arrAirportId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 결과 -->\n");
      out.write("    <div class=\"tp-card\">\n");
      out.write("<div class=\"tp-body\">\n");
      out.write("        ");
      if (_jspx_meth_j_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        ");
      if (_jspx_meth_j_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("<style>\n");
      out.write("  .ptf-footer{\n");
      out.write("    margin-top:auto; /* ✅ 짧은 페이지에서 하단 고정 */\n");
      out.write("    padding-bottom: 24px;\n");
      out.write("    background:#fff;\n");
      out.write("    color:#111827;\n");
      out.write("    position:relative;\n");
      out.write("    z-index:10;\n");
      out.write("    margin-top:0;\n");
      out.write("    /* ✅ 전체 페이지 공통 footer: 가로 스크롤(100vw) 방지 */\n");
      out.write("    width:100%;\n");
      out.write("    margin-left:0;\n");
      out.write("    box-sizing:border-box;\n");
      out.write("    overflow-x:hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write("  /* 상단 파란 포인트 라인(그대로 유지) */\n");
      out.write("  .ptf-footer__topbar{\n");
      out.write("    height:3px;\n");
      out.write("    background: linear-gradient(90deg,#2f6fed 0%, #5b8cff 50%, #2f6fed 100%);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* 링크 메뉴 영역(그대로 유지) */\n");
      out.write("  .ptf-footer__nav{\n");
      out.write("    border-bottom:1px solid #e5e7eb;\n");
      out.write("    padding:14px 0;\n");
      out.write("    background:#fff;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px;\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:space-between;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("    gap:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links a{\n");
      out.write("    font-size:13px;\n");
      out.write("    font-weight:600;\n");
      out.write("    color:#374151;\n");
      out.write("    text-decoration:none;\n");
      out.write("    padding:4px 14px;\n");
      out.write("    border-right:1px solid #d1d5db;\n");
      out.write("    transition:color .15s;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__nav-links a:first-child{ padding-left:0; }\n");
      out.write("  .ptf-footer__nav-links a:last-child{ border-right:none; }\n");
      out.write("  .ptf-footer__nav-links a:hover{ color:#2f6fed; }\n");
      out.write("  .ptf-footer__nav-links a.pt-highlight{\n");
      out.write("    color:#2f6fed;\n");
      out.write("    font-weight:800;\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" /* ========== 메인 정보 영역 (로고 + 프로젝트 정보) ========== */\n");
      out.write("  /* 메인 정보 영역(큰 박스) */\n");
      out.write("  .ptf-footer__body{\n");
      out.write("    padding:32px 0 0;              /* ✅ 아래는 bottombar가 따로 있으니 0 */\n");
      out.write("    border-bottom:1px solid #e5e7eb;\n");
      out.write("    background:#fff;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__body-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px 22px;           /* ✅ 박스 안 내용 아래 여백 */\n");
      out.write("    display:grid;\n");
      out.write("    grid-template-columns:220px 1fr;\n");
      out.write("    gap:48px;\n");
      out.write("    align-items:start;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .ptf-footer__brand-logo{\n");
      out.write("    font-size:24px;\n");
      out.write("    font-weight:900;\n");
      out.write("    color:#111827;\n");
      out.write("    letter-spacing:-.3px;\n");
      out.write("    margin-bottom:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__brand-logo span{ color:#2f6fed; }\n");
      out.write("\n");
      out.write("/* ---- 왼쪽: 브랜드 설명 텍스트 ---- */\n");
      out.write("  .ptf-footer__brand-desc{\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#6b7280;\n");
      out.write("    line-height:1.6;\n");
      out.write("    margin:0;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("/* ---- 오른쪽: 프로젝트 정보 영역 ---- */\n");
      out.write("  .ptf-footer__info{\n");
      out.write("    display:flex;\n");
      out.write("    flex-direction:column;\n");
      out.write("    gap:10px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__info-row{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("    gap:6px 20px;\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#374151;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__info-row .pt-sep{ color:#d1d5db; }\n");
      out.write("  .ptf-footer__info-row strong{ font-weight:700; color:#111827; }\n");
      out.write("\n");
      out.write("  .ptf-footer__contact-item{\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    gap:6px;\n");
      out.write("    font-size:13px;\n");
      out.write("    color:#374151;\n");
      out.write("    margin-top:4px;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__contact-item a{\n");
      out.write("    color:#374151;\n");
      out.write("    text-decoration:underline;\n");
      out.write("    text-underline-offset:3px;\n");
      out.write("    transition:color .15s;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__contact-item a:hover{ color:#2f6fed; }\n");
      out.write("  .ptf-footer__contact-item .pt-icon{\n");
      out.write("    width:18px;\n");
      out.write("    height:18px;\n");
      out.write("    background:#f3f4f6;\n");
      out.write("    border-radius:50%;\n");
      out.write("    display:inline-flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:center;\n");
      out.write("    font-size:10px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ✅ 동그라미 문구를 \"화살표 박스 안\"에 붙이는 하단 바 */\n");
      out.write("  .ptf-footer__bottombar{\n");
      out.write("    background:#f3f4f6;                 /* ✅ 회색(연한) 배경으로 '붙어' 보이게 */\n");
      out.write("    border-top:1px solid #e5e7eb;       /* ✅ 박스 안에서 딱 붙는 구분선 */\n");
      out.write("    padding:12px 0;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__bottombar-inner{\n");
      out.write("    max-width:1200px;\n");
      out.write("    margin:0 auto;\n");
      out.write("    padding:0 24px;\n");
      out.write("    display:flex;\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:space-between;      /* ✅ 좌/우 */\n");
      out.write("    gap:16px;\n");
      out.write("    flex-wrap:wrap;\n");
      out.write("  }\n");
      out.write("  .ptf-footer__copy,\n");
      out.write("  .ptf-footer__note{\n");
      out.write("    margin:0;\n");
      out.write("    font-size:13px;\n");
      out.write("    line-height:1.5;\n");
      out.write("    color:rgba(17,24,39,.70);\n");
      out.write("  }\n");
      out.write("  .ptf-footer__note{ text-align:right; }\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("  @media (max-width:860px){\n");
      out.write("    .ptf-footer__body-inner{ grid-template-columns:1fr; gap:24px; }\n");
      out.write("    .ptf-footer__nav-links a{ font-size:12px; padding:4px 10px; }\n");
      out.write("  }\n");
      out.write("  @media (max-width:768px){\n");
      out.write("    .ptf-footer__bottombar-inner{\n");
      out.write("      flex-direction:column;\n");
      out.write("      align-items:flex-start;\n");
      out.write("    }\n");
      out.write("    .ptf-footer__note{ text-align:left; }\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ===== Floating 고객센터 (기존 UI 그대로) ===== */\n");
      out.write("  .cs-fab{\n");
      out.write("    position:fixed;\n");
      out.write("    right:26px;\n");
      out.write("    bottom:26px;\n");
      out.write("    z-index:9999;\n");
      out.write("    height:56px;\n");
      out.write("    min-width:78px;\n");
      out.write("    padding:10px 14px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    background:rgba(47,111,237,.92);\n");
      out.write("    backdrop-filter:blur(6px);\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.18);\n");
      out.write("    display:inline-flex;\n");
      out.write("    align-items:center;\n");
      out.write("    gap:10px;\n");
      out.write("    border:1px solid rgba(255,255,255,.18);\n");
      out.write("    user-select:none;\n");
      out.write("    -webkit-tap-highlight-color:transparent;\n");
      out.write("    text-decoration:none;\n");
      out.write("  }\n");
      out.write("  .cs-fab__icon{\n");
      out.write("    width:38px;\n");
      out.write("    height:38px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    background:#fff;\n");
      out.write("    color:#2f6fed;\n");
      out.write("    display:grid;\n");
      out.write("    place-items:center;\n");
      out.write("    font-weight:900;\n");
      out.write("    font-size:18px;\n");
      out.write("    flex:0 0 auto;\n");
      out.write("  }\n");
      out.write("  .cs-fab__label{\n");
      out.write("    color:#fff;\n");
      out.write("    font-weight:900;\n");
      out.write("    font-size:14px;\n");
      out.write("    letter-spacing:-.2px;\n");
      out.write("    max-width:0;\n");
      out.write("    opacity:0;\n");
      out.write("    transform:translateX(6px);\n");
      out.write("    overflow:hidden;\n");
      out.write("    white-space:nowrap;\n");
      out.write("    transition:max-width .22s ease, opacity .18s ease, transform .22s ease;\n");
      out.write("  }\n");
      out.write("  .cs-fab:hover{\n");
      out.write("    background:rgba(47,111,237,1);\n");
      out.write("    transform:translateY(-2px);\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.22);\n");
      out.write("  }\n");
      out.write("  .cs-fab:hover .cs-fab__label{\n");
      out.write("    max-width:140px;\n");
      out.write("    opacity:1;\n");
      out.write("    transform:translateX(0);\n");
      out.write("  }\n");
      out.write("  .cs-fab:focus-visible{\n");
      out.write("    outline:none;\n");
      out.write("    box-shadow:0 0 0 4px rgba(47,111,237,.25), 0 22px 50px rgba(0,0,0,.22);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /* ===== 맨 위로 버튼 (고객센터 위에) ===== */\n");
      out.write("  .top-fab{\n");
      out.write("    position:fixed;\n");
      out.write("    right:26px;\n");
      out.write("    bottom:92px; /* 고객센터 위 */\n");
      out.write("    z-index:9999;\n");
      out.write("    width:56px;\n");
      out.write("    height:56px;\n");
      out.write("    border-radius:999px;\n");
      out.write("    border:1px solid rgba(17,24,39,.10);\n");
      out.write("    background:#fff;\n");
      out.write("    box-shadow:0 18px 40px rgba(0,0,0,.14);\n");
      out.write("    display:none; /* 스크롤 시 JS로 표시 */\n");
      out.write("    align-items:center;\n");
      out.write("    justify-content:center;\n");
      out.write("    cursor:pointer;\n");
      out.write("    -webkit-tap-highlight-color:transparent;\n");
      out.write("  }\n");
      out.write("  .top-fab:hover{\n");
      out.write("    transform:translateY(-2px);\n");
      out.write("    box-shadow:0 22px 50px rgba(0,0,0,.18);\n");
      out.write("  }\n");
      out.write("  .top-fab svg{\n");
      out.write("    width:22px;\n");
      out.write("    height:22px;\n");
      out.write("    stroke:#2f6fed;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<footer class=\"ptf-footer\" role=\"contentinfo\">\n");
      out.write("\n");
      out.write("  <!-- 상단 포인트 라인 -->\n");
      out.write("  <div class=\"ptf-footer__topbar\"></div>\n");
      out.write("\n");
      out.write("  <!-- 링크 메뉴 -->\n");
      out.write("  <nav class=\"ptf-footer__nav\">\n");
      out.write("    <div class=\"ptf-footer__nav-inner\">\n");
      out.write("      <div class=\"ptf-footer__nav-links\">\n");
      out.write("        <a href=\"#\" class=\"pt-highlight\">개인정보 취급방침</a>\n");
      out.write("        <a href=\"#\">이용약관</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <!-- 메인 정보(화살표 친 큰 박스) -->\n");
      out.write("  <div class=\"ptf-footer__body\">\n");
      out.write("    <div class=\"ptf-footer__body-inner\">\n");
      out.write("\n");
      out.write("      <div class=\"ptf-footer__brand\">\n");
      out.write("        <div class=\"ptf-footer__brand-logo\">Plan<span>Trip</span></div>\n");
      out.write("        <p class=\"ptf-footer__brand-desc\">\n");
      out.write("          나만의 여행을 더 쉽게,<br>더 똑똑하게.\n");
      out.write("        </p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"ptf-footer__info\">\n");
      out.write("        <div class=\"ptf-footer__info-row\">\n");
      out.write("          <span>프로젝트 : <strong>PlanTrip (교육용 팀 프로젝트)</strong></span>\n");
      out.write("          <span class=\"pt-sep\">|</span>\n");
      out.write("          <span>소속 : <strong>백석대학교</strong></span>\n");
      out.write("          <span class=\"pt-sep\">|</span>\n");
      out.write("          <span>강의실 : <strong>214호</strong></span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"ptf-footer__info-row\">\n");
      out.write("          <span>충청남도 천안시 동남구 백석대학로 1 &nbsp;백석대학교 (214호 강의실)</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"ptf-footer__contact-item\">\n");
      out.write("          <span class=\"pt-icon\">✉</span>\n");
      out.write("          <a href=\"mailto:plantrip.team@baekseok.ac.kr\">plantrip.team@baekseok.ac.kr</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- ✅ 동그라미 문구를 \"화살표 박스 안\" 맨 아래에 붙임 -->\n");
      out.write("    <div class=\"ptf-footer__bottombar\">\n");
      out.write("      <div class=\"ptf-footer__bottombar-inner\">\n");
      out.write("        <p class=\"ptf-footer__copy\">© <span id=\"ptFooterYear\"></span> PlanTrip. All Rights Reserved.</p>\n");
      out.write("        <p class=\"ptf-footer__note\">본 사이트는 교육용 프로젝트이며 실제 예약/결제 기능을 제공하지 않습니다.</p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Floating: 맨 위로 / 고객센터 -->\n");
      out.write("<button class=\"top-fab\" type=\"button\" aria-label=\"맨 위로\">\n");
      out.write("  <svg viewBox=\"0 0 24 24\" fill=\"none\" aria-hidden=\"true\">\n");
      out.write("    <path d=\"M12 5l-7 7m7-7l7 7M12 5v14\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"></path>\n");
      out.write("  </svg>\n");
      out.write("</button>\n");
      out.write("\n");
      out.write("<a class=\"cs-fab\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/support\" aria-label=\"고객센터\">\n");
      out.write("  <span class=\"cs-fab__icon\" aria-hidden=\"true\">?</span>\n");
      out.write("  <span class=\"cs-fab__label\">고객센터</span>\n");
      out.write("</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  document.body.setAttribute('data-ctx', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/fabs.js\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  (function(){\n");
      out.write("    var el = document.getElementById('ptFooterYear');\n");
      out.write("    if(el) el.textContent = new Date().getFullYear();\n");
      out.write("  })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- ✅ Toast UI : 전 페이지 공통 (로그인/저장/안내 메시지) -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/ui-toast.css\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/ui-toast.js\"></script>\n");
      out.write("\n");
      out.write("<!-- ✅ Auth Modal (Login/Signup) : 전 페이지 공통 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/auth-modal.css\" />\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-modal.js\"></script>\n");
      out.write("<script defer src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/auth-guard.js\"></script>\n");
      out.write("<!-- auth-modal ê³µíµ include -->\n");
      out.write("\n");
      out.write("<!-- 로그인 모달 -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-login\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authLoginTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\n");
      out.write("\n");
      out.write("    <!-- ✅ dialog 전체에 깔리는 물결 배경 -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-wrap auth-wrap--split\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authLoginTitle\">로그인</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/login\" method=\"post\">\n");
      out.write("          <div class=\"label\">아이디</div>\n");
      out.write("          <input class=\"input\" name=\"id\" type=\"text\" placeholder=\"아이디\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">비밀번호</div>\n");
      out.write("          <div class=\"input-row\">\n");
      out.write("            <input class=\"input\" name=\"password\" type=\"password\" placeholder=\"비밀번호\" required />\n");
      out.write("            <span class=\"eye\" role=\"button\" tabindex=\"0\" aria-label=\"비밀번호 보기\">👁</span>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div style=\"text-align:right; margin-top:-6px;\">\n");
      out.write("            <a class=\"underline small\" href=\"/members/find-password\" data-auth-switch=\"find\">비밀번호를 잊으셨나요?</a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">로그인</button>\n");
      out.write("\n");
      out.write("          <div class=\"social-row\">\n");
      out.write("            <button class=\"social-btn\" type=\"button\"><span class=\"social-dot\"></span> 구글</button>\n");
      out.write("            <button class=\"social-btn\" type=\"button\"><span class=\"social-dot\"></span> 페이스북</button>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            계정이 없으신가요?\n");
      out.write("            <a class=\"underline\" href=\"/members/register\" data-auth-switch=\"signup\"><b>회원가입</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("\n");
      out.write("<!-- 회원가입 모달 -->\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-signup\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authSignupTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\n");
      out.write("\n");
      out.write("    <!-- dialog 전체에 깔리는 물결/물방울 배경 (회원가입은 CSS에서 “왼쪽” 앵커 처리됨) -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <!-- [수정] 회원가입은 폼이 오른쪽으로 가야 하므로 auth-wrap--swap 사용 -->\n");
      out.write("    <div class=\"auth-wrap auth-wrap--swap\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authSignupTitle\">회원가입</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/register\" method=\"post\">\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <div class=\"label\">이름</div>\n");
      out.write("          <input class=\"input\" name=\"mName\" type=\"text\" placeholder=\"이름\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">아이디</div>\n");
      out.write("          <input class=\"input\" name=\"mId\" type=\"text\" placeholder=\"아이디\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">이메일</div>\n");
      out.write("          <input class=\"input\" name=\"mEmail\" type=\"email\" placeholder=\"이메일\" required />\n");
      out.write("\n");
      out.write("          <div class=\"label\">비밀번호</div>\n");
      out.write("          <div class=\"input-row\">\n");
      out.write("            <input class=\"input\" name=\"mPw\" type=\"password\" placeholder=\"비밀번호\" required />\n");
      out.write("            <span class=\"eye\" role=\"button\" tabindex=\"0\" aria-label=\"비밀번호 보기\">👁</span>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">회원가입</button>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            이미 회원이신가요?\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>로그인</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- [수정] 오른쪽(또는 왼쪽) 빈 자리용: 배경은 wave-bg가 담당 -->\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("<!-- 비밀번호 찾기(재설정 링크) 모달 -->\n");
      out.write("\n");
      out.write("<div class=\"auth-modal\" id=\"authModal-find\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"auth-modal__backdrop\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("  <div class=\"auth-modal__dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"authFindTitle\" tabindex=\"-1\">\n");
      out.write("    <button class=\"auth-modal__close\" type=\"button\" data-auth-close aria-label=\"닫기\">✕</button>\n");
      out.write("\n");
      out.write("    <!-- ✅ dialog 전체 물결 배경(센터 정렬 버전) -->\n");
      out.write("    <div class=\"auth-modal__wave-bg\" aria-hidden=\"true\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"auth-wrap auth-wrap--center\">\n");
      out.write("      <div class=\"auth-left\">\n");
      out.write("        <div class=\"brand\">\n");
      out.write("          <div class=\"logo\">TP</div>\n");
      out.write("          <div class=\"title\" id=\"authFindTitle\">비밀번호 찾기</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <form class=\"form\" action=\"/members/find-password\" method=\"post\" data-find-form>\n");
      out.write("          <div class=\"label\">가입 이메일</div>\n");
      out.write("          <input class=\"input\" name=\"email\" type=\"email\" placeholder=\"example@email.com\" required />\n");
      out.write("\n");
      out.write("          <div class=\"helper\">\n");
      out.write("            입력하신 이메일로 <b>비밀번호 재설정 링크</b>를 보내드립니다.<br/>\n");
      out.write("            링크는 일정 시간 후 만료됩니다.\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-error\" data-auth-error style=\"display:none;\"></div>\n");
      out.write("\n");
      out.write("          <button class=\"primary-btn\" type=\"submit\">재설정 링크 받기</button>\n");
      out.write("\n");
      out.write("          <div class=\"auth-footer\">\n");
      out.write("            <a class=\"underline\" href=\"/members/login\" data-auth-switch=\"login\"><b>로그인으로</b></a>\n");
      out.write("          </div>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"auth-right\" aria-hidden=\"true\"></div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write("\n");
      out.write("<div class=\"lr-modal\" id=\"loginRequiredModal\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"lr-backdrop\" data-lr-close></div>\n");
      out.write("\n");
      out.write("  <div class=\"lr-dialog\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"lrTitle\" tabindex=\"-1\">\n");
      out.write("    <div class=\"lr-icon\" aria-hidden=\"true\">🔒</div>\n");
      out.write("    <h2 class=\"lr-title\" id=\"lrTitle\">로그인이 필요한 작업입니다</h2>\n");
      out.write("    <p class=\"lr-desc\" id=\"lrDesc\">계속하려면 로그인해 주세요.</p>\n");
      out.write("\n");
      out.write("    <div class=\"lr-actions\">\n");
      out.write("      <button type=\"button\" class=\"lr-btn ghost\" data-lr-cancel>취소</button>\n");
      out.write("      <button type=\"button\" class=\"lr-btn solid\" data-lr-confirm>확인</button>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_j_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_j_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_j_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_j_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/transport/flight.jsp(84,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f0.setVar("a");
    // /WEB-INF/views/transport/flight.jsp(84,18) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/transport/flight.jsp(84,18) '${airports}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${airports}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_j_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_j_005fforEach_005f0 = _jspx_th_j_005fforEach_005f0.doStartTag();
      if (_jspx_eval_j_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    ");
          if (_jspx_meth_j_005fif_005f0(_jspx_th_j_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_j_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_j_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_j_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_j_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_j_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_j_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_j_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_j_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fforEach_005f0);
    // /WEB-INF/views/transport/flight.jsp(85,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.key != 'NAARKPC'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f0 = _jspx_th_j_005fif_005f0.doStartTag();
    if (_jspx_eval_j_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                      <button type=\"button\"\n");
        out.write("                              class=\"tp-chip ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.key == (empty depAirportId ? 'NAARKPC' : depAirportId) ? 'is-active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\n");
        out.write("                              data-air-id=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.key}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\n");
        out.write("                        ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.value}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("                      </button>\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_j_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_j_005fforEach_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_j_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_j_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_j_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/transport/flight.jsp(102,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f1.setVar("a");
    // /WEB-INF/views/transport/flight.jsp(102,18) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/transport/flight.jsp(102,18) '${airports}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${airports}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_j_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_j_005fforEach_005f1 = _jspx_th_j_005fforEach_005f1.doStartTag();
      if (_jspx_eval_j_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    ");
          if (_jspx_meth_j_005fif_005f1(_jspx_th_j_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_j_005fforEach_005f1))
            return true;
          out.write("\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_j_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_j_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_j_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_j_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_j_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_j_005fforEach_005f1);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fforEach_005f1, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_j_005fforEach_005f1)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fforEach_005f1);
    // /WEB-INF/views/transport/flight.jsp(103,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.key != 'NAARKPC'}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f1 = _jspx_th_j_005fif_005f1.doStartTag();
    if (_jspx_eval_j_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                      <button type=\"button\"\n");
        out.write("                              class=\"tp-chip ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.key == (empty arrAirportId ? selectedAirportId : arrAirportId) ? 'is-active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\n");
        out.write("                              data-air-id=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.key}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\n");
        out.write("                        ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${a.value}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("                      </button>\n");
        out.write("                    ");
        int evalDoAfterBody = _jspx_th_j_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f2.setParent(null);
    // /WEB-INF/views/transport/flight.jsp(127,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty result}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f2 = _jspx_th_j_005fif_005f2.doStartTag();
    if (_jspx_eval_j_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("          <div class=\"tp-empty\">조회 결과가 없습니다.</div>\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_j_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f3.setParent(null);
    // /WEB-INF/views/transport/flight.jsp(131,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty result}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f3 = _jspx_th_j_005fif_005f3.doStartTag();
    if (_jspx_eval_j_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("          <div class=\"tp-table-wrap\">\n");
        out.write("            <table class=\"tp-table\">\n");
        out.write("              <thead>\n");
        out.write("              <tr>\n");
        out.write("                <th>편명</th>\n");
        out.write("                <th>항공사</th>\n");
        out.write("                <th>출발공항</th>\n");
        out.write("                <th>도착공항</th>\n");
        out.write("                <th>출발시각</th>\n");
        out.write("                <th>도착시각</th>\n");
        out.write("              </tr>\n");
        out.write("              </thead>\n");
        out.write("              <tbody>\n");
        out.write("              ");
        if (_jspx_meth_j_005fforEach_005f2(_jspx_th_j_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("              </tbody>\n");
        out.write("            </table>\n");
        out.write("          </div>\n");
        out.write("\n");
        out.write("          <div class=\"tp-pagination\">\n");
        out.write("    ");
        if (_jspx_meth_j_005fforEach_005f3(_jspx_th_j_005fif_005f3, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("  </div>\n");
        int evalDoAfterBody = _jspx_th_j_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_j_005fforEach_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fif_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_j_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_j_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_j_005fforEach_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fif_005f3);
    // /WEB-INF/views/transport/flight.jsp(145,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f2.setVar("r");
    // /WEB-INF/views/transport/flight.jsp(145,14) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/transport/flight.jsp(145,14) '${result}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${result}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_j_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_j_005fforEach_005f2 = _jspx_th_j_005fforEach_005f2.doStartTag();
      if (_jspx_eval_j_005fforEach_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                <tr>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.vihicleId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.airlineNm}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.depAirportNm}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.arrAirportNm}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.depTimeText}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                  <td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${r.arrTimeText}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\n");
          out.write("                </tr>\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_j_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_j_005fforEach_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_j_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_j_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_j_005fforEach_005f2.doFinally();
    }
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_j_005fforEach_005f2);
    return false;
  }

  private boolean _jspx_meth_j_005fforEach_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fif_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_j_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_j_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_j_005fforEach_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fif_005f3);
    // /WEB-INF/views/transport/flight.jsp(160,4) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f3.setBegin(1);
    // /WEB-INF/views/transport/flight.jsp(160,4) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f3.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPages}", int.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
    // /WEB-INF/views/transport/flight.jsp(160,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fforEach_005f3.setVar("p");
    int[] _jspx_push_body_count_j_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_j_005fforEach_005f3 = _jspx_th_j_005fforEach_005f3.doStartTag();
      if (_jspx_eval_j_005fforEach_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("      ");
          if (_jspx_meth_j_005fif_005f4(_jspx_th_j_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_j_005fforEach_005f3))
            return true;
          out.write("\n");
          out.write("      ");
          if (_jspx_meth_j_005fif_005f5(_jspx_th_j_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_j_005fforEach_005f3))
            return true;
          out.write("\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_j_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_j_005fforEach_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_j_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_j_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_j_005fforEach_005f3.doFinally();
    }
    _005fjspx_005ftagPool_005fj_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_j_005fforEach_005f3);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f4(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fforEach_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_j_005fforEach_005f3)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f4.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fforEach_005f3);
    // /WEB-INF/views/transport/flight.jsp(161,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty depAirportId && not empty arrAirportId}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f4 = _jspx_th_j_005fif_005f4.doStartTag();
    if (_jspx_eval_j_005fif_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        <a class=\"tp-pagebtn ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p == currentPage ? 'is-active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\n");
        out.write("           href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/transport/flight/search?depAirportId=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depAirportId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&arrAirportId=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${arrAirportId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&depPlandTime=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\n");
        out.write("          ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("        </a>\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_j_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_j_005fif_005f5(jakarta.servlet.jsp.tagext.JspTag _jspx_th_j_005fforEach_005f3, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_j_005fforEach_005f3)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  j:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_j_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_j_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_j_005fif_005f5.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_j_005fforEach_005f3);
    // /WEB-INF/views/transport/flight.jsp(167,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_j_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty depAirportId || empty arrAirportId}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_j_005fif_005f5 = _jspx_th_j_005fif_005f5.doStartTag();
    if (_jspx_eval_j_005fif_005f5 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        <a class=\"tp-pagebtn ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p == currentPage ? 'is-active' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"\n");
        out.write("           href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/transport/flight?airportId=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedAirportId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&depPlandTime=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depPlandTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&direction=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${direction}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&page=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\n");
        out.write("          ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\n");
        out.write("        </a>\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_j_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_j_005fif_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fj_005fif_0026_005ftest.reuse(_jspx_th_j_005fif_005f5);
    return false;
  }
}
